"""
team_registry.py — Единый реестр алиасов команд.
TEAM_ALIASES и clean_team_name в одном модуле (§19.2).
Устраняет циклическую зависимость между hub и search_module.
"""

import logging

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

__all__ = ["TEAM_ALIASES", "clean_team_name", "normalize_team_name", "build_canonical_id", "__version__"]

# ── TEAM_ALIASES — 257+ записей ─────────────────────────────
TEAM_ALIASES = {
    # England
    "man united": "man",
    "man utd": "man",
    "manchester united": "man",
    "man city": "man_city",
    "manchester city": "man_city",
    "nott'm forest": "nottingham_forest",
    "nottingham forest": "nottingham_forest",
    "spurs": "tottenham",
    "tottenham hotspur": "tottenham",
    "tottenham": "tottenham",
    "arsenal": "arsenal",
    "chelsea": "chelsea",
    "liverpool": "liverpool",
    "everton": "everton",
    "newcastle": "newcastle",
    "newcastle united": "newcastle",
    "west ham": "west_ham",
    "west ham united": "west_ham",
    "aston villa": "aston_villa",
    "fulham": "fulham",
    "brighton": "brighton",
    "brighton & hove albion": "brighton",
    "crystal palace": "crystal_palace",
    "brentford": "brentford",
    "wolves": "wolverhampton",
    "wolverhampton": "wolverhampton",
    "wolverhampton wanderers": "wolverhampton",
    "leeds": "leeds",
    "leeds united": "leeds",
    "southampton": "southampton",
    "burnley": "burnley",
    "watford": "watford",
    "norwich": "norwich",
    "norwich city": "norwich",
    "leicester": "leicester",
    "leicester city": "leicester",
    "bournemouth": "bournemouth",
    "luton": "luton",
    "luton town": "luton",
    "sheffield united": "sheffield_united",
    "sheffield utd": "sheffield_united",
    "qpr": "qpr",
    "queens park rangers": "qpr",
    "hull": "hull",
    "hull city": "hull",
    "middlesbrough": "middlesbrough",
    "sunderland": "sunderland",
    "bristol city": "bristol_city",
    "cardiff": "cardiff",
    "cardiff city": "cardiff",
    "swansea": "swansea",
    "swansea city": "swansea",
    "reading": "reading",
    "wigan": "wigan",
    "wigan athletic": "wigan",
    "blackburn": "blackburn",
    "blackburn rovers": "blackburn",
    "birmingham": "birmingham",
    "birmingham city": "birmingham",
    "stoke": "stoke",
    "stoke city": "stoke",
    "west brom": "west_brom",
    "west bromwich albion": "west_brom",
    "derby": "derby",
    "derby county": "derby",
    "coventry": "coventry",
    "coventry city": "coventry",
    "ipswich": "ipswich",
    "ipswich town": "ipswich",
    "millwall": "millwall",
    "preston": "preston",
    "preston north end": "preston",
    "rotherham": "rotherham",
    "rotherham united": "rotherham",
    "plymouth": "plymouth",
    "plymouth argyle": "plymouth",
    "huddersfield": "huddersfield",
    "huddersfield town": "huddersfield",

    # Spain
    "barcelona": "barcelona",
    "fc barcelona": "barcelona",
    "real madrid": "real_madrid",
    "atletico madrid": "atletico_madrid",
    "atletico": "atletico_madrid",
    "athletic bilbao": "athletic_bilbao",
    "athletic club": "athletic_bilbao",
    "sevilla": "sevilla",
    "real sociedad": "real_sociedad",
    "villarreal": "villarreal",
    "real betis": "real_betis",
    "betis": "real_betis",
    "valencia": "valencia",
    "celta vigo": "celta_vigo",
    "celta": "celta_vigo",
    "getafe": "getafe",
    "osasuna": "osasuna",
    "rayo vallecano": "rayo_vallecano",
    "rayo": "rayo_vallecano",
    "mallorca": "mallorca",
    "alaves": "alaves",
    "deportivo alaves": "alaves",
    "girona": "girona",
    "las palmas": "las_palmas",
    "ud las palmas": "las_palmas",
    "cadiz": "cadiz",
    "cadiz cf": "cadiz",
    "granada": "granada",
    "granada cf": "granada",
    "almeria": "almeria",
    "ud almeria": "almeria",
    "elche": "elche",
    "elche cf": "elche",
    "espanyol": "espanyol",
    "rcd espanyol": "espanyol",
    "levant": "levante",
    "levante": "levante",
    "valladolid": "valladolid",
    "real valladolid": "valladolid",

    # Italy
    "juventus": "juventus",
    "juve": "juventus",
    "inter": "inter",
    "inter milan": "inter",
    "internazionale": "inter",
    "ac milan": "milan",
    "milan": "milan",
    "roma": "roma",
    "as roma": "roma",
    "lazio": "lazio",
    "ss lazio": "lazio",
    "napoli": "napoli",
    "naples": "napoli",
    "atalanta": "atalanta",
    "fiorentina": "fiorentina",
    "torino": "torino",
    "bologna": "bologna",
    "monza": "monza",
    "udinese": "udinese",
    "udinese calcio": "udinese",
    "sassuolo": "sassuolo",
    "empoli": "empoli",
    "hellas verona": "verona",
    "verona": "verona",
    "cagliari": "cagliari",
    "lecce": "lecce",
    "salernitana": "salernitana",
    "cremonese": "cremonese",
    "spezia": "spezia",
    "sampdoria": "sampdoria",
    "genoa": "genoa",
    "geno": "genoa",
    "frosinone": "frosinone",
    "como": "como",
    "venezia": "venezia",
    "venezia fc": "venezia",
    "parma": "parma",
    "parma calcio": "parma",
    "pisa": "pisa",

    # Germany
    "bayern munich": "bayern",
    "bayern": "bayern",
    "fc bayern": "bayern",
    "dortmund": "dortmund",
    "borussia dortmund": "dortmund",
    "bvb": "dortmund",
    "leverkusen": "leverkusen",
    "bayer leverkusen": "leverkusen",
    "rb leipzig": "rb_leipzig",
    "leipzig": "rb_leipzig",
    "union berlin": "union_berlin",
    "union": "union_berlin",
    "freiburg": "freiburg",
    "sc freiburg": "freiburg",
    "eintracht frankfurt": "frankfurt",
    "frankfurt": "frankfurt",
    "wolfsburg": "wolfsburg",
    "vfl wolfsburg": "wolfsburg",
    "mainz": "mainz",
    "mainz 05": "mainz",
    "borussia monchengladbach": "monchengladbach",
    "monchengladbach": "monchengladbach",
    "gladbach": "monchengladbach",
    "werder bremen": "bremen",
    "bremen": "bremen",
    "augsburg": "augsburg",
    "fc augsburg": "augsburg",
    "hoffenheim": "hoffenheim",
    "1899 hoffenheim": "hoffenheim",
    "bochum": "bochum",
    "vfl bochum": "bochum",
    "stuttgart": "stuttgart",
    "vfb stuttgart": "stuttgart",
    "hertha": "hertha",
    "hertha bsc": "hertha",
    "hamburg": "hamburg",
    "hsv": "hamburg",
    "hamburger sv": "hamburg",
    "schalke": "schalke",
    "schalke 04": "schalke",
    "cologne": "cologne",
    "koln": "cologne",
    "fc koln": "cologne",
    "darmstadt": "darmstadt",
    "darmstadt 98": "darmstadt",
    "heidenheim": "heidenheim",
    "1. fc heidenheim": "heidenheim",
    "kaiserslautern": "kaiserslautern",
    "1. fc kaiserslautern": "kaiserslautern",
    "paderborn": "paderborn",
    "sc paderborn": "paderborn",
    "furth": "furth",
    "greuther furth": "furth",
    "dusseldorf": "dusseldorf",
    "fortuna dusseldorf": "dusseldorf",
    "karlsruher": "karlsruher",
    "karlsruhe": "karlsruher",
    "hannover": "hannover",
    "hannover 96": "hannover",
    "braunschweig": "braunschweig",

    # France
    "psg": "psg",
    "paris saint germain": "psg",
    "paris saint-germain": "psg",
    "paris sg": "psg",
    "marseille": "marseille",
    "om": "marseille",
    "olympique marseille": "marseille",
    "lyon": "lyon",
    "ol": "lyon",
    "olympique lyonnais": "lyon",
    "monaco": "monaco",
    "as monaco": "monaco",
    "lille": "lille",
    "losc": "lille",
    "lille osc": "lille",
    "rennes": "rennes",
    "stade rennais": "rennes",
    "nice": "nice",
    "ogc nice": "nice",
    "lens": "lens",
    "rc lens": "lens",
    "nantes": "nantes",
    "fc nantes": "nantes",
    "montpellier": "montpellier",
    "montpellier hsc": "montpellier",
    "strasbourg": "strasbourg",
    "rc strasbourg": "strasbourg",
    "brest": "brest",
    "stade brestois": "brest",
    "toulouse": "toulouse",
    "toulouse fc": "toulouse",
    "auxerre": "auxerre",
    "aj auxerre": "auxerre",
    "angers": "angers",
    "angers sco": "angers",
    "lorient": "lorient",
    "fc lorient": "lorient",
    "clermont": "clermont",
    "clermont foot": "clermont",
    "reims": "reims",
    "stade de reims": "reims",
    "metz": "metz",
    "fc metz": "metz",
    "le havre": "le_havre",
    "hac": "le_havre",

    # Portugal
    "benfica": "benfica",
    "sl benfica": "benfica",
    "porto": "porto",
    "fc porto": "porto",
    "sporting": "sporting",
    "sporting cp": "sporting",
    "braga": "braga",
    "sc braga": "braga",
    "vitoria guimaraes": "vitoria_guimaraes",
    "guimaraes": "vitoria_guimaraes",
    "famalicao": "famalicao",
    "fc famalicao": "famalicao",
    "boavista": "boavista",
    "boavista fc": "boavista",
    "moreirense": "moreirense",
    "moreirense fc": "moreirense",
    "rio ave": "rio_ave",
    "rio ave fc": "rio_ave",
    "estoril": "estoril",
    "estoril praia": "estoril",
    "casa pia": "casa_pia",
    "casa pia ac": "casa_pia",
    "vizela": "vizela",
    "fc vizela": "vizela",
    "portimonense": "portimonense",
    "gil vicente": "gil_vicente",
    "estrela": "estrela",
    "estrela amadora": "estrela",
    "arouca": "arouca",
    "fc arouca": "arouca",
    "chaves": "chaves",
    "gd chaves": "chaves",

    # Netherlands
    "ajax": "ajax",
    "afc ajax": "ajax",
    "psv": "psv",
    "psv eindhoven": "psv",
    "feyenoord": "feyenoord",
    "az alkmaar": "az",
    "az": "az",
    "twente": "twente",
    "fc twente": "twente",
    "utrecht": "utrecht",
    "fc utrecht": "utrecht",
    "vitesse": "vitesse",
    "sc heerenveen": "heerenveen",
    "heerenveen": "heerenveen",
    "sparta rotterdam": "sparta_rotterdam",
    "sparta": "sparta_rotterdam",
    "nec": "nec",
    "nec nijmegen": "nec",
    "fortuna sittard": "fortuna_sittard",
    "fortuna": "fortuna_sittard",
    "groningen": "groningen",
    "fc groningen": "groningen",
    "heracles": "heracles",
    "heracles almelo": "heracles",
    "go ahead eagles": "go_ahead_eagles",
    "excelsior": "excelsior",
    "sbv excelsior": "excelsior",
    "emmen": "emmen",
    "fc emmen": "emmen",
    "zwolle": "zwolle",
    "pec zwolle": "zwolle",
    "almere": "almere",
    "almere city": "almere",
    "waalwijk": "waalwijk",
    "rc waalwijk": "waalwijk",
    "breda": "breda",
    "nac breda": "breda",

    # Brazil
    "palmeiras": "palmeiras",
    "flamengo": "flamengo",
    "corinthians": "corinthians",
    "sao paulo": "sao_paulo",
    "fluminense": "fluminense",
    "atletico mineiro": "atletico_mineiro",
    "galo": "atletico_mineiro",
    "internacional": "internacional",
    "colorado": "internacional",
    "gremio": "gremio",
    "cruzeiro": "cruzeiro",
    "botafogo": "botafogo",
    "vasco": "vasco",
    "vasco da gama": "vasco",
    "atletico paranaense": "athletico_paranaense",
    "athletico": "athletico_paranaense",
    "bahia": "bahia",
    "ec bahia": "bahia",
    "fortaleza": "fortaleza",
    "ceara": "ceara",
    "ceara sc": "ceara",
    "santos": "santos",
    "juventude": "juventude",
    "cuiaba": "cuiaba",
    "cuiaba ec": "cuiaba",
    "bragantino": "bragantino",
    "rb bragantino": "bragantino",
    "atletico goianiense": "atletico_goianiense",
    "vitoria": "vitoria_ba",
    "ec vitoria": "vitoria_ba",
    "criciuma": "criciuma",
    "criciuma ec": "criciuma",
    "chapecoense": "chapecoense",
    "coritiba": "coritiba",
    "goias": "goias",
    "goias ec": "goias",
    "america mineiro": "america_mineiro",
    "america mg": "america_mineiro",

    # Argentina
    "river plate": "river_plate",
    "boca juniors": "boca_juniors",
    "boca": "boca_juniors",
    "racing club": "racing_club",
    "racing": "racing_club",
    "independiente": "independiente",
    "san lorenzo": "san_lorenzo",
    "estudiantes": "estudiantes",
    "estudiantes lp": "estudiantes",
    "lanus": "lanus",
    "newell's old boys": "newells_old_boys",
    "newells": "newells_old_boys",
    "rosario central": "rosario_central",
    "belgrano": "belgrano",
    "defensa y justicia": "defensa_y_justicia",
    "godoy cruz": "godoy_cruz",
    "talleres": "talleres",
    "talleres cordoba": "talleres",
    "union santa fe": "union_santa_fe",
    "instituto": "instituto",
    "instituto cordoba": "instituto",
    "platenense": "platense",
    "platense": "platense",
    "sarmiento": "sarmiento",
    "central cordoba": "central_cordoba",
    "huracan": "huracan",
    "barracas central": "barracas_central",
    "tigre": "tigre",
    "colon": "colon",
    "colon santa fe": "colon",
    "argentinos juniors": "argentinos_juniors",
    "banfield": "banfield",
    "gimnasia": "gimnasia",
    "gimnasia lp": "gimnasia",
    "velez sarsfield": "velez_sarsfield",
    "velez": "velez_sarsfield",

    # Mexico
    "club america": "club_america",
    "america": "club_america",
    "guadalajara": "guadalajara",
    "chivas": "guadalajara",
    "monterrey": "monterrey",
    "rayados": "monterrey",
    "tigres": "tigres",
    "tigres uanl": "tigres",
    "cruz azul": "cruz_azul",
    "pumas": "pumas",
    "pumas unam": "pumas",
    "toluca": "toluca",
    "deportivo toluca": "toluca",
    "pachuca": "pachuca",
    "cf pachuca": "pachuca",
    "tijuana": "tijuana",
    "club tijuana": "tijuana",
    "santos laguna": "santos_laguna",
    "atlas": "atlas",
    "club atlas": "atlas",
    "atletico san luis": "atletico_san_luis",
    "san luis": "atletico_san_luis",
    "leon": "leon",
    "club leon": "leon",
    "puebla": "puebla",
    "club puebla": "puebla",
    "queretaro": "queretaro",
    "club queretaro": "queretaro",
    "juarez": "juarez",
    "fc juarez": "juarez",
    "mazatlan": "mazatlan",
    "mazatlan fc": "mazatlan",
    "necaxa": "necaxa",
    "club necaxa": "necaxa",

    # Turkey
    "galatasaray": "galatasaray",
    "fenerbahce": "fenerbahce",
    "besiktas": "besiktas",
    "trabzonspor": "trabzonspor",
    "basaksehir": "basaksehir",
    "istanbul basaksehir": "basaksehir",
    "adana demirspor": "adana_demirspor",
    "konyaspor": "konyaspor",
    "antalyaspor": "antalyaspor",
    "kasimpasa": "kasimpasa",
    "alanyaspor": "alanyaspor",
    "gaziantep": "gaziantep",
    "gaziantep fk": "gaziantep",
    "rizespor": "rizespor",
    "caykur rizespor": "rizespor",
    "samsunspor": "samsunspor",
    "kayserispor": "kayserispor",
    "ankaragucu": "ankaragucu",
    "mke ankaragucu": "ankaragucu",
    "hatayspor": "hatayspor",
    "pendikspor": "pendikspor",

    # Scotland
    "celtic": "celtic",
    "celtic glasgow": "celtic",
    "rangers": "rangers",
    "glasgow rangers": "rangers",
    "aberdeen": "aberdeen",
    "hearts": "hearts",
    "heart of midlothian": "hearts",
    "hibernian": "hibernian",
    "hibs": "hibernian",
    "kilmarnock": "kilmarnock",
    "motherwell": "motherwell",
    "st mirren": "st_mirren",
    "st johnstone": "st_johnstone",
    "ross county": "ross_county",
    "dundee": "dundee",
    "dundee united": "dundee_united",
    "dundee fc": "dundee",

    # Belgium
    "anderlecht": "anderlecht",
    "rsc anderlecht": "anderlecht",
    "club brugge": "club_brugge",
    "brugge": "club_brugge",
    "gent": "gent",
    "kaa gent": "gent",
    "antwerp": "antwerp",
    "royal antwerp": "antwerp",
    "union sg": "union_sg",
    "st. gilloise": "union_sg",
    "union saint-gilloise": "union_sg",
    "genk": "genk",
    "krc genk": "genk",
    "standard liege": "standard_liege",
    "standard": "standard_liege",
    "mechelen": "mechelen",
    "kv mechelen": "mechelen",
    "cercle brugge": "cercle_brugge",
    "stvv": "stvv",
    "sint-truiden": "stvv",
    "kortrijk": "kortrijk",
    "kv kortrijk": "kortrijk",
    "oh leuven": "oh_leuven",
    "leuven": "oh_leuven",
    "eupen": "eupen",
    "as eupen": "eupen",
    "charleroi": "charleroi",
    "sporting charleroi": "charleroi",
    "westerlo": "westerlo",
    "kvc westerlo": "westerlo",

    # Greece
    "olympiacos": "olympiacos",
    "panathinaikos": "panathinaikos",
    "paok": "paok",
    "aek athens": "aek_athens",
    "aek": "aek_athens",
    "panionios": "panionios",
    "ofi": "ofi",
    "ofi crete": "ofi",
    "asteras tripolis": "asteras_tripolis",
    "asteras": "asteras_tripolis",
    "aris": "aris",
    "aris thessaloniki": "aris",
    "atromitos": "atromitos",
    "volos": "volos",
    "volos nfl": "volos",
    "lamia": "lamia",

    # Switzerland
    "young boys": "young_boys",
    "bsc young boys": "young_boys",
    "basel": "basel",
    "fc basel": "basel",
    "zurich": "zurich",
    "fc zurich": "zurich",
    "luzern": "luzern",
    "fc luzern": "luzern",
    "st. gallen": "st_gallen",
    "st gallen": "st_gallen",
    "servette": "servette",
    "fc servette": "servette",
    "lausanne": "lausanne",
    "fc lausanne": "lausanne",
    "lugano": "lugano",
    "fc lugano": "lugano",
    "winterthur": "winterthur",
    "fc winterthur": "winterthur",
    "grasshopper": "grasshopper",
    "gc": "grasshopper",

    # Austria
    "rb salzburg": "rb_salzburg",
    "salzburg": "rb_salzburg",
    "sturm graz": "sturm_graz",
    "rapid vienna": "rapid_vienna",
    "rapid": "rapid_vienna",
    "austria vienna": "austria_vienna",
    "austria wien": "austria_vienna",
    "lask": "lask",
    "wsg tirol": "wsg_tirol",
    "tirol": "wsg_tirol",
    "wolfsberger": "wolfsberger",
    "wolfsberg": "wolfsberger",
    "altach": "altach",
    "scr altach": "altach",
    "klusaturm": "klusaturm",
    "hartberg": "hartberg",
    "tsv hartberg": "hartberg",
    "bw linz": "bw_linz",
    "blau-wei linz": "bw_linz",
    "ried": "ried",
    "sv ried": "ried",

    # Denmark
    "copenhagen": "copenhagen",
    "fc copenhagen": "copenhagen",
    "kbh": "copenhagen",
    "midtjylland": "midtjylland",
    "fc midtjylland": "midtjylland",
    "brondby": "brondby",
    "brondby if": "brondby",
    "agf": "agf",
    "agf aarhus": "agf",
    "aarhus": "agf",
    "aalborg": "aalborg",
    "aalborg bk": "aalborg",
    "viborg": "viborg",
    "viborg ff": "viborg",
    "nordsjaelland": "nordsjaelland",
    "fc nordsjaelland": "nordsjaelland",
    "vejle": "vejle",
    "vejle bk": "vejle",
    "silkeborg": "silkeborg",
    "silkeborg if": "silkeborg",
    "lyngby": "lyngby",
    "lyngby bk": "lyngby",
    "hvidovre": "hvidovre",
    "hvidovre if": "hvidovre",
    "odense": "odense",
    "odense bk": "odense",
    "ob": "odense",

    # Poland
    "legia warsaw": "legia_warsaw",
    "legia": "legia_warsaw",
    "lech poznan": "lech_poznan",
    "lech": "lech_poznan",
    "rakow czestochowa": "rakow",
    "rakow": "rakow",
    "pogon szczecin": "pogon_szczecin",
    "pogon": "pogon_szczecin",
    "wisl": "wisl",
    "wisla": "wisl",
    "wisla krakow": "wisl",
    "piast gliwice": "piast_gliwice",
    "piast": "piast_gliwice",
    "zaglebie lubin": "zaglebie_lubin",
    "zaglebie": "zaglebie_lubin",
    "warta poznan": "warta_poznan",
    "warta": "warta_poznan",
    "radomiak": "radomiak",
    "radomiak radom": "radomiak",
    "widzew lodz": "widzew_lodz",
    "widzew": "widzew_lodz",
    "gornik zabrze": "gornik_zabrze",
    "gornik": "gornik_zabrze",
    "cracovia": "cracovia",
    "ks cracovia": "cracovia",
    "korona kielce": "korona_kielce",
    "korona": "korona_kielce",
    "lukasz": "lukasz",

    # Sweden
    "malmo": "malmo_ff",
    "malmo ff": "malmo_ff",
    "hacken": "hacken",
    "bk hacken": "hacken",
    "djugardens": "djugardens",
    "djurgardens": "djugardens",
    "hammarby": "hammarby",
    "if elfsborg": "elfsborg",
    "elfsborg": "elfsborg",
    "kalmar": "kalmar",
    "kalmar ff": "kalmar",
    "halmstad": "halmstad",
    "halmstads bk": "halmstad",
    "vasteras": "vasteras",
    "vasteras sk": "vasteras",
    "varbergs": "varbergs",
    "varbergs bois": "varbergs",
    "mjalby": "mjalby",
    "mjalby aif": "mjalby",
    "gais": "gais",
    "goteborg": "ifk_goteborg",
    "ifk goteborg": "ifk_goteborg",
    "sirius": "sirius",
    "ik sirius": "sirius",
    "brostrop": "brostrop",
    "ifk varnamo": "varnamo",
    "varnamo": "varnamo",
    "degerfors": "degerfors",
    "degerfors if": "degerfors",
    "ai stockholm": "ai",
    "aik": "ai",

    # Norway
    "molde": "molde",
    "molde fk": "molde",
    "rosenborg": "rosenborg",
    "rbk": "rosenborg",
    "bodoe/glimt": "bodo_glimt",
    "bodo/glimt": "bodo_glimt",
    "glimt": "bodo_glimt",
    "brann": "brann",
    "sk brann": "brann",
    "viking": "viking",
    "viking fk": "viking",
    "lillestrom": "lillestrom",
    "lillestrom sk": "lillestrom",
    "stromsgodset": "stromsgodset",
    "odd": "odd",
    "odd grenland": "odd",
    "sarpsborg 08": "sarpsborg",
    "sarpsborg": "sarpsborg",
    "hamkam": "hamkam",
    "ham-kam": "hamkam",
    "aalesund": "aalesund",
    "aafk": "aalesund",
    "kristiansund": "kristiansund",
    "kbk": "kristiansund",
    "tromsoe": "tromso",
    "tromso": "tromso",
    "til": "tromso",
    "haugesund": "haugesund",
    "fkh": "haugesund",
    "sandefjord": "sandefjord",
    "sff": "sandefjord",
    "start": "start",
    "ik start": "start",

    # MLS / USA
    "inter miami": "inter_miami",
    "la galaxy": "la_galaxy",
    "galaxy": "la_galaxy",
    "new york red bulls": "ny_red_bulls",
    "ny red bulls": "ny_red_bulls",
    "red bulls": "ny_red_bulls",
    "fc cincinnati": "cincinnati",
    "cincinnati": "cincinnati",
    "orlando city": "orlando_city",
    "orlando": "orlando_city",
    "atlanta united": "atlanta_united",
    "atlanta": "atlanta_united",
    "nashville": "nashville",
    "nashville sc": "nashville",
    "philadelphia union": "philadelphia",
    "phila union": "philadelphia",
    "columbus crew": "columbus_crew",
    "columbus": "columbus_crew",
    "seattle sounders": "seattle",
    "seattle": "seattle",
    "sounders": "seattle",
    "portland timbers": "portland_timbers",
    "portland": "portland_timbers",
    "timbers": "portland_timbers",
    "austin": "austin",
    "austin fc": "austin",
    "charlotte": "charlotte",
    "charlotte fc": "charlotte",
    "chicago fire": "chicago_fire",
    "chicago": "chicago_fire",
    "dallas": "dallas",
    "fc dallas": "dallas",
    "houston dynamo": "houston_dynamo",
    "houston": "houston_dynamo",
    "dynamo": "houston_dynamo",
    "kansas city": "kansas_city",
    "sporting kansas city": "kansas_city",
    "sporting kc": "kansas_city",
    "real salt lake": "real_salt_lake",
    "salt lake": "real_salt_lake",
    "dc united": "dc_united",
    "dcu": "dc_united",
    "new england revolution": "new_england",
    "new england": "new_england",
    "revolution": "new_england",
    "toronto fc": "toronto_fc",
    "toronto": "toronto_fc",
    "vancouver whitecaps": "vancouver_whitecaps",
    "vancouver": "vancouver_whitecaps",
    "whitecaps": "vancouver_whitecaps",
    "montreal": "montreal",
    "cf montreal": "montreal",
    "st. louis": "st_louis",
    "st louis city": "st_louis",
    "st louis city sc": "st_louis",
    "san jose earthquakes": "san_jose",
    "san jose": "san_jose",
    "earthquakes": "san_jose",
    "colorado rapids": "colorado_rapids",

    # Japan (J-League)
    "kashima antlers": "kashima_antlers",
    "kashima": "kashima_antlers",
    "yokohama f marinos": "yokohama_f_marinos",
    "yokohama fm": "yokohama_f_marinos",
    "kawasaki frontale": "kawasaki_frontale",
    "kawasaki": "kawasaki_frontale",
    "urawa red diamonds": "urawa_reds",
    "urawa reds": "urawa_reds",
    "urawa": "urawa_reds",
    "gamba osaka": "gamba_osaka",
    "cerezo osaka": "cerezo_osaka",
    "nagoya grampus": "nagoya_grampus",
    "nagoya": "nagoya_grampus",
    "fc tokyo": "fc_tokyo",
    "tokyo": "fc_tokyo",
    "shimizu s-pulse": "shimizu_s_pulse",
    "shimizu": "shimizu_s_pulse",
    "sanfrecce hiroshima": "sanfrecce_hiroshima",
    "hiroshima": "sanfrecce_hiroshima",
    "vissel kobe": "vissel_kobe",
    "kobe": "vissel_kobe",
    "sagan tosu": "sagan_tosu",
    "tosu": "sagan_tosu",
    "consadole sapporo": "consadole_sapporo",
    "sapporo": "consadole_sapporo",
    "avispa fukuoka": "avispa_fukuoka",
    "fukuoka": "avispa_fukuoka",
    "jubilo iwata": "jubilo_iwata",
    "iwata": "jubilo_iwata",
    "shonan bellmare": "shonan_bellmare",
    "shonan": "shonan_bellmare",
    "kashiwa reysol": "kashiwa_reysol",
    "kashiwa": "kashiwa_reysol",
    "albirex niigata": "albirex_niigata",
    "niigata": "albirex_niigata",
    "machida zavia": "machida_zavia",
    "machida": "machida_zavia",
# Netherlands — Eredivisie
    "ajax": "ajax",
    "afc ajax": "ajax",
    "psv": "psv",
    "psv eindhoven": "psv",
    "feyenoord": "feyenoord",
    "az alkmaar": "az_alkmaar",
    "az": "az_alkmaar",
    "fc twente": "twente",
    "twente": "twente",
    "fc utrecht": "utrecht",
    "utrecht": "utrecht",
    "sc heerenveen": "heerenveen",
    "heerenveen": "heerenveen",
    "sparta rotterdam": "sparta_rotterdam",
    "sparta": "sparta_rotterdam",
    "nec": "nec",
    "nec nijmegen": "nec",
    "vitesse": "vitesse",
    "go ahead eagles": "go_ahead_eagles",
    "go ahead": "go_ahead_eagles",
    "fortuna sittard": "fortuna_sittard",
    "fortuna": "fortuna_sittard",
    "sc cambuur": "cambuur",
    "cambuur": "cambuur",
    "fc emmen": "emmen",
    "emmen": "emmen",
    "waalwijk": "waalwijk",
    "rkc waalwijk": "waalwijk",
    "fc groningen": "groningen",
    "groningen": "groningen",
    "pec zwolle": "zwolle",
    "zwolle": "zwolle",
    "heracles": "heracles",
    "heracles almelo": "heracles",
    "excelsior": "excelsior",
    "sbv excitelsior": "excelsior",

    # Turkey — Süper Lig
    "galatasaray": "galatasaray",
    "fenerbahce": "fenerbahce",
    "fenerbahçe": "fenerbahce",
    "besiktas": "besiktas",
    "beşiktaş": "besiktas",
    "trabzonspor": "trabzonspor",
    "basaksehir": "basaksehir",
    "istanbul basaksehir": "basaksehir",
    "adana demirspor": "adana_demirspor",
    "adana": "adana_demirspor",
    "antalyaspor": "antalyaspor",
    "antalya": "antalyaspor",
    "kasimpasa": "kasimpasa",
    "alanyaspor": "alanyaspor",
    "alanya": "alanyaspor",
    "kayserispor": "kayserispor",
    "konyaspor": "konyaspor",
    "konya": "konyaspor",
    "gaziantep": "gaziantep",
    "gaziantep fk": "gaziantep",
    "gazişehri gaziantep": "gaziantep",
    "sivasspor": "sivasspor",
    "sivas": "sivasspor",
    "rizespor": "rizespor",
    "çaykur rizespor": "rizespor",
    "giresunspor": "giresunspor",
    "giresun": "giresunspor",
    "malatyaspor": "malatyaspor",
    "yeni malatyaspor": "malatyaspor",
    "hatayspor": "hatayspor",
    "hatay": "hatayspor",
    "ankaragucu": "ankaragucu",
    "ankaragücü": "ankaragucu",
    "mersin idman yurdu": "mersin",
    "mersin": "mersin",
    "karakabhoptmetallurg": "karakabhoptmetallurg",
    "boluspor": "boluspor",
    "bolu": "boluspor",
    "umraniyespor": "umraniyespor",

    # Belgium — Jupiler Pro League
    "club brugge": "club_brugge",
    "club brügge": "club_brugge",
    "anderlecht": "anderlecht",
    "rsc anderlecht": "anderlecht",
    "krc genk": "genk",
    "genk": "genk",
    "royal antwerp": "antwerp",
    "antwerp": "antwerp",
    "union sg": "union_sg",
    "union saint-gilloise": "union_sg",
    "sg union": "union_sg",
    "gent": "gent",
    "kaa gent": "gent",
    "standard liege": "standard_liege",
    "standard liège": "standard_liege",
    "standard": "standard_liege",
    "mechelen": "mechelen",
    "kv mechelen": "mechelen",
    "charleroi": "charleroi",
    "sporting charleroi": "charleroi",
    "kortrijk": "kortrijk",
    "kv kortrijk": "kortrijk",
    "ostende": "ostende",
    "kv ostende": "ostende",
    "cercle brugge": "cercle_brugge",
    "sint truiden": "sint_truiden",
    "sint-truiden": "sint_truiden",
    "stvv": "sint_truiden",
    "eupen": "eupen",
    "beerschot": "beerschot",
    "zulte waregem": "zulte_waregem",
    "zulte-waregem": "zulte_waregem",
    "sv zulte waregem": "zulte_waregem",
    "oh leuven": "oh_leuven",
    "leuven": "oh_leuven",
    "waasland-beveren": "waasland_beveren",
    "waasland beveren": "waasland_beveren",
    "sebastien"  : "sebastien",
}


def clean_team_name(name: str) -> str:
    """
    Нормализация названия команды (§4).
    1. Приведение к нижнему регистру + нормализация диакритиков
    2. Поиск в TEAM_ALIASES (оригинальный ключ, до нормализации)
    3. Удаление спецсимволов + повторный поиск
    4. Удаление суффиксов (fc, cf, afc, united, city, town, sc, club, bk, if, ac, as) + повторный поиск
    5. Нормализация слэшей и дефисов + повторный поиск
    6. Fallback — заменяем пробелы на подчёркивания

    Возвращает нормализованную версию (home_clean/away_clean).
    """
    if not name or not isinstance(name, str):
        return ""

    try:
        # FIX-AUDIT: Нормализация диакритиков (Köln -> koln, Malmö -> malmo)
        # FIX-AUDIT-v9.3: Manual mapping for chars that NFD doesn't decompose
        # ø, æ, ð, þ, ß are single codepoints, not composable — NFD leaves them as-is
        _SPECIAL_CHARS = str.maketrans({
            "ø": "o", "Ø": "o",
            "æ": "ae", "Æ": "ae",
            "ð": "d", "Ð": "d",
            "þ": "th", "Þ": "th",
            "ß": "ss",
            "ł": "l", "Ł": "l",
            "đ": "d", "Đ": "d",
            "ı": "i", "İ": "i",
        })
        name = name.translate(_SPECIAL_CHARS)
        import unicodedata
        normalized = unicodedata.normalize("NFD", name)
        key = "".join(c for c in normalized if unicodedata.category(c) != "Mn")
        key = key.strip().lower()

        # Шаг 1: Прямой lookup (оригинальный ключ с апострофами)
        if key in TEAM_ALIASES:
            return TEAM_ALIASES[key]

        # Шаг 2: Удаление спецсимволов + lookup
        clean_key = key.replace("'", "").replace(".", "").replace(",", "")
        clean_key = clean_key.replace("  ", " ").strip()
        if clean_key in TEAM_ALIASES:
            return TEAM_ALIASES[clean_key]

        # Шаг 3: Удаление суффиксов (только с конца) + lookup
        # FIX-AUDIT: добавлены " bk", " if", " ac", " as" для скандинавских и латинских команд
        suffixes = [" fc", " cf", " afc", " sc", " united", " city", " town",
                    " club", " bk", " if", " ac", " as"]
        stripped = clean_key
        for suffix in suffixes:
            if stripped.endswith(suffix):
                stripped = stripped[:-len(suffix)].strip()
                break  # only strip one suffix
        if stripped in TEAM_ALIASES:
            return TEAM_ALIASES[stripped]

        # Шаг 4: Нормализация слэшей и дефисов + lookup
        # FIX-AUDIT: "bodoe/glimt" -> "bodoeglimt" -> lookup, "ham-kam" -> "hamkam"
        slash_key = clean_key.replace("/", "").replace("-", " ").strip()
        if slash_key in TEAM_ALIASES:
            return TEAM_ALIASES[slash_key]
        slash_key2 = slash_key.replace(" ", "")
        if slash_key2 in TEAM_ALIASES:
            return TEAM_ALIASES[slash_key2]

        # Шаг 5: Fallback — заменяем пробелы на подчёркивания
        return stripped.replace(" ", "_")
    except Exception as e:
        logger.warning("clean_team_name error for %r: %s", name, e)
        return ""


def build_canonical_id(home: str, away: str, date_str: str) -> str:
    """
    Строит canonical_id (§1.18): home__away__YYYYMMDD.
    Использует clean_team_name для нормализации команд.
    date_str — ISO 8601 или YYYY-MM-DD.
    """
    try:
        h = clean_team_name(home) or home.strip().lower().replace(" ", "_")
        a = clean_team_name(away) or away.strip().lower().replace(" ", "_")
        # Извлекаем YYYYMMDD из date_str
        d = date_str.strip() if date_str else ""
        if "T" in d:
            d = d.split("T")[0]
        d = d.replace("-", "")
        # FIX-AUDIT: Валидация даты — 8 цифр
        if len(d) != 8 or not d.isdigit():
            logger.warning("build_canonical_id: invalid date %r", date_str)
            return ""
        return f"{h}__{a}__{d}"
    except Exception as e:
        logger.warning("build_canonical_id error: %s", e)
        return ""



def normalize_team_name(name: str) -> str:
    """
    Синоним для clean_team_name.
    Коллекторы (odds_api, bzzoiro) импортируют normalize_team_name.
    """
    return clean_team_name(name)

__version__ = "9.3-audited"

# __all__ moved to top
