"""
team_registry.py — v9.3-audited
Canonical team name registry + normalization for GatekeeperAI
~2850 aliases / ~1500 unique teams / 58 countries
"""

__version__ = "9.3-audited"


# ============================================================
# TEAM_ALIASES — alias -> canonical
# ============================================================

TEAM_ALIASES = {

    # ============================================================

    # ============================================================

    # === ENGLAND — Premier League + Championship + League One + League Two + National ===
    "arsenal": "arsenal",
    "arsenal fc": "arsenal",
    "chelsea": "chelsea",
    "chelsea fc": "chelsea",
    "liverpool": "liverpool",
    "liverpool fc": "liverpool",
    "manchester city": "city",
    "man city": "city",
    "manchester united": "man",
    "man utd": "man",
    "man united": "man",
    "tottenham": "tottenham",
    "spurs": "tottenham",
    "tottenham hotspur": "tottenham",
    "hotspur": "tottenham",
    "everton": "everton",
    "newcastle": "newcastle",
    "newcastle united": "newcastle",
    "aston villa": "aston_villa",
    "brighton": "brighton",
    "brighton hove albion": "brighton",
    "west ham": "west_ham",
    "west ham united": "west_ham",
    "crystal palace": "crystal_palace",
    "brentford": "brentford",
    "fulham": "fulham",
    "wolverhampton": "wolverhampton",
    "wolves": "wolverhampton",
    "nottingham forest": "nottingham_forest",
    "nottm forest": "nottingham_forest",
    "nott'm forest": "nottingham_forest",
    "burnley": "burnley",
    "luton": "luton",
    "luton town": "luton",
    "the hatters": "luton",
    "sheffield united": "sheffield_united",
    "sheffield utd": "sheffield_united",
    "afc bournemouth": "bournemouth",
    "bournemouth": "bournemouth",
    "leicester": "leicester",
    "leicester city": "leicester",
    "leeds": "leeds",
    "leeds united": "leeds",
    "southampton": "southampton",
    "norwich": "norwich",
    "norwich city": "norwich",
    "watford": "watford",
    "west brom": "west_brom",
    "west bromwich albion": "west_brom",
    "west bromwich": "west_brom",
    "stoke city": "stoke",
    "stoke": "stoke",
    "hull city": "hull",
    "hull": "hull",
    "cardiff": "cardiff",
    "cardiff city": "cardiff",
    "swansea": "swansea",
    "swansea city": "swansea",
    "birmingham": "birmingham",
    "birmingham city": "birmingham",
    "blackburn": "blackburn",
    "blackburn rovers": "blackburn",
    "millwall": "millwall",
    "qpr": "qpr",
    "queens park rangers": "qpr",
    "reading": "reading",
    "barnsley": "barnsley",
    "bristol city": "bristol_city",
    "derby county": "derby",
    "derby": "derby",
    "ipswich": "ipswich",
    "ipswich town": "ipswich",
    "middlesbrough": "middlesbrough",
    "boro": "middlesbrough",
    "preston": "preston",
    "preston north end": "preston",
    "rotherham": "rotherham",
    "rotherham united": "rotherham",
    "sunderland": "sunderland",
    "swindon": "swindon",
    "swindon town": "swindon",
    "wigan": "wigan",
    "wigan athletic": "wigan",
    "bolton": "bolton",
    "bolton wanderers": "bolton",
    "charlton": "charlton",
    "charlton athletic": "charlton",
    "portsmouth": "portsmouth",
    "oxford united": "oxford_united",
    "oxford": "oxford_united",
    "cambridge united": "cambridge_united",
    "cambridge": "cambridge_united",
    "exeter": "exeter",
    "exeter city": "exeter",
    "fleetwood": "fleetwood",
    "fleetwood town": "fleetwood",
    "lincoln": "lincoln",
    "lincoln city": "lincoln",
    "morecambe": "morecambe",
    "accrington": "accrington",
    "accrington stanley": "accrington",
    "shrewsbury": "shrewsbury",
    "shrewsbury town": "shrewsbury",
    "cheltenham": "cheltenham",
    "cheltenham town": "cheltenham",
    "bristol rovers": "bristol_rovers",
    "burton albion": "burton",
    "burton": "burton",
    "wimbledon": "afc_wimbledon",
    "afc wimbledon": "afc_wimbledon",
    "doncaster": "doncaster",
    "doncaster rovers": "doncaster",
    "peterborough": "peterborough",
    "peterborough united": "peterborough",
    "plymouth": "plymouth",
    "plymouth argyle": "plymouth",
    "rochdale": "rochdale",
    "salford": "salford",
    "salford city": "salford",
    "stockport": "stockport",
    "stockport county": "stockport",
    "walsall": "walsall",
    "barrow": "barrow",
    "barrow afc": "barrow",
    "bradford": "bradford",
    "bradford city": "bradford",
    "colchester": "colchester",
    "colchester united": "colchester",
    "crawley": "crawley",
    "crawley town": "crawley",
    "gillingham": "gillingham",
    "harrow": "harrow",
    "hartlepool": "hartlepool",
    "hartlepool united": "hartlepool",
    "newport": "newport",
    "newport county": "newport",
    "sutton": "sutton",
    "sutton united": "sutton",
    "tranmere": "tranmere",
    "tranmere rovers": "tranmere",
    "mansfield": "mansfield",
    "mansfield town": "mansfield",
    "stevenage": "stevenage",
    "grimsby": "grimsby",
    "grimsby town": "grimsby",
    "crewe": "crewe",
    "crewe alexandra": "crewe",
    "harrogate": "harrogate",
    "harrogate town": "harrogate",
    "carlisle": "carlisle",
    "carlisle united": "carlisle",
    "scunthorpe": "scunthorpe",
    "scunthorpe united": "scunthorpe",
    "northampton": "northampton",
    "northampton town": "northampton",
    "wrexham": "wrexham",
    "notts county": "notts_county",
    "leyton orient": "leyton_orient",
    "forest green": "forest_green",
    "forest green rovers": "forest_green",

    # === SPAIN — La Liga + Segunda ===
    "real madrid": "real_madrid",
    "barcelona": "barcelona",
    "fc barcelona": "barcelona",
    "atletico madrid": "atletico_madrid",
    "atletico": "atletico_madrid",
    "athletic bilbao": "athletic_bilbao",
    "athletic club": "athletic_bilbao",
    "real sociedad": "real_sociedad",
    "villarreal": "villarreal",
    "betis": "betis",
    "real betis": "betis",
    "sevilla": "sevilla",
    "valencia": "valencia",
    "celta vigo": "celta_vigo",
    "celta": "celta_vigo",
    "rayo vallecano": "rayo_vallecano",
    "rayo": "rayo_vallecano",
    "osasuna": "osasuna",
    "mallorca": "mallorca",
    "getafe": "getafe",
    "alaves": "alaves",
    "deportivo alaves": "alaves",
    "cadiz": "cadiz",
    "granada": "granada",
    "las palmas": "las_palmas",
    "almeria": "almeria",
    "girona": "girona",
    "elche": "elche",
    "espanyol": "espanyol",
    "rcd espanyol": "espanyol",
    "levante": "levante",
    "real oviedo": "real_oviedo",
    "oviedo": "real_oviedo",
    "sporting gijon": "sporting_gijon",
    "gijon": "sporting_gijon",
    "tenerife": "tenerife",
    "cd tenerife": "tenerife",
    "valladolid": "valladolid",
    "real valladolid": "valladolid",
    "burgos": "burgos",
    "eibar": "eibar",
    "sd eibar": "eibar",
    "cartagena": "fc_cartagena",
    "fc cartagena": "fc_cartagena",
    "murcia": "real_murcia",
    "real murcia": "real_murcia",
    "castellon": "castellon",
    "cd castellon": "castellon",
    "huesca": "huesca",
    "sd huesca": "huesca",
    "fuenlabrada": "fuenlabrada",
    "alcorcon": "alcorcon",
    "leganes": "leganes",
    "cd leganes": "leganes",
    "mirandas": "mirandas",
    "ponferradina": "ponferradina",
    "albacete": "albacete",
    "lugo": "lugo",
    "cd lugo": "lugo",
    "ibiza": "ibiza",
    "ibiza ud": "ibiza",
    "amorebieta": "amorebieta",
    "real zaragoza": "zaragoza",
    "zaragoza": "zaragoza",
    "malaga": "malaga",
    "deportivo": "deportivo_la_coruna",
    "deportivo la coruna": "deportivo_la_coruna",

    # === ITALY — Serie A + Serie B ===
    "inter": "inter_milan",
    "inter milan": "inter_milan",
    "fc internazionale": "inter_milan",
    "internazionale": "inter_milan",
    "milan": "milan",
    "ac milan": "milan",
    "juventus": "juventus",
    "juve": "juventus",
    "napoli": "napoli",
    "ssc napoli": "napoli",
    "roma": "roma",
    "as roma": "roma",
    "lazio": "lazio",
    "ss lazio": "lazio",
    "atalanta": "atalanta",
    "fiorentina": "fiorentina",
    "acf fiorentina": "fiorentina",
    "torino": "torino",
    "toro": "torino",
    "il toro": "torino",
    "bologna": "bologna",
    "monza": "monza",
    "udinese": "udinese",
    "sassuolo": "sassuolo",
    "salernitana": "salernitana",
    "empoli": "empoli",
    "hellas verona": "hellas_verona",
    "verona": "hellas_verona",
    "lecce": "lecce",
    "spezia": "spezia",
    "cremonese": "cremonese",
    "sampdoria": "sampdoria",
    "unione sampdoria": "sampdoria",
    "genoa": "genoa",
    "cagliari": "cagliari",
    "frosinone": "frosinone",
    "parma": "parma",
    "como": "como",
    "venezia": "venezia",
    "venezia fc": "venezia",
    "reggina": "reggina",
    "modena": "modena",
    "brescia": "brescia",
    "ternana": "ternana",
    "terni": "ternana",
    "bari": "bari",
    "as bari": "bari",
    "pisa": "pisa",
    "cittadella": "cittadella",
    "cosenza": "cosenza",
    "spal": "spal",
    "benevento": "benevento",
    "reggiana": "reggiana",
    "perugia": "perugia",
    "ascoli": "ascoli",
    "palermo": "palermo",
    "foggia": "foggia",
    "pordenone": "pordenone",
    "vicenza": "vicenza",
    "alessandria": "alessandria",
    "cesena": "cesena",
    "south tyrol": "south_tyrol",
    "bolzano": "south_tyrol",
    "sudtirol": "south_tyrol",
    "el verona": "hellas_verona",
    "lecco": "lecco",

    # === GERMANY — Bundesliga + 2. Bundesliga + Liga 3 ===
    "bayern munich": "bayern_munich",
    "bayern": "bayern_munich",
    "fc bayern": "bayern_munich",
    "borussia dortmund": "dortmund",
    "dortmund": "dortmund",
    "bvb": "dortmund",
    "rb leipzig": "rb_leipzig",
    "leipzig": "rb_leipzig",
    "leverkusen": "leverkusen",
    "bayer leverkusen": "leverkusen",
    "frankfurt": "frankfurt",
    "eintracht frankfurt": "frankfurt",
    "wolfsburg": "wolfsburg",
    "vfl wolfsburg": "wolfsburg",
    "mainz": "mainz",
    "mainz 05": "mainz",
    "freiburg": "freiburg",
    "sc freiburg": "freiburg",
    "hoffenheim": "hoffenheim",
    "1899 hoffenheim": "hoffenheim",
    "union berlin": "union_berlin",
    "werder bremen": "werder_bremen",
    "bremen": "werder_bremen",
    "borussia monchengladbach": "monchengladbach",
    "monchengladbach": "monchengladbach",
    "gladbach": "monchengladbach",
    "augsburg": "augsburg",
    "fc augsburg": "augsburg",
    "bochum": "bochum",
    "vfl bochum": "bochum",
    "stuttgart": "stuttgart",
    "vfb stuttgart": "stuttgart",
    "hertha berlin": "hertha_berlin",
    "hertha": "hertha_berlin",
    "schalke": "schalke",
    "schalke 04": "schalke",
    "hamburg": "hamburg",
    "hsv": "hamburg",
    "hannover 96": "hannover_96",
    "hannover": "hannover_96",
    "nurnberg": "nurnberg",
    "1 fc nurnberg": "nurnberg",
    "darmstadt": "darmstadt",
    "sv darmstadt 98": "darmstadt",
    "karlsruher": "karlsruher",
    "karlsruhe": "karlsruher",
    "paderborn": "paderborn",
    "sc paderborn": "paderborn",
    "kaiserslautern": "kaiserslautern",
    "1 fc kaiserslautern": "kaiserslautern",
    "braunschweig": "braunschweig",
    "eintracht braunschweig": "braunschweig",
    "magdeburg": "magdeburg",
    "1 fc magdeburg": "magdeburg",
    "dusseldorf": "dusseldorf",
    "fortuna dusseldorf": "dusseldorf",
    "kiel": "kiel",
    "holstein kiel": "kiel",
    "heidenheim": "heidenheim",
    "1 fc heidenheim": "heidenheim",
    "greuther furth": "greuther_furth",
    "furth": "greuther_furth",
    "sandhausen": "sandhausen",
    "sv sandhausen": "sandhausen",
    "arminia bielefeld": "bielefeld",
    "bielefeld": "bielefeld",
    "ingolstadt": "ingolstadt",
    "fc ingolstadt": "ingolstadt",
    "erzgebirge aue": "aue",
    "aue": "aue",
    "osnabruck": "osnabruck",
    "vfl osnabruck": "osnabruck",
    "wurzburger kickers": "wurzburg",
    "wurzburg": "wurzburg",
    "dynamo dresden": "dresden",
    "dresden": "dresden",
    "hansa rostock": "rostock",
    "rostock": "rostock",
    "wehen": "wehen",
    "sv wehen wiesbaden": "wehen",
    "wiesbaden": "wehen",
    "waldhof mannheim": "mannheim",
    "mannheim": "mannheim",
    "saarbrucken": "saarbrucken",
    "1 fc saarbrucken": "saarbrucken",
    "meppen": "meppen",
    "sv meppen": "meppen",
    "verl": "verl",
    "sc verl": "verl",
    "viktoria koln": "viktoria_koln",
    "bavel": "bavel",

    # === FRANCE — Ligue 1 + Ligue 2 ===
    "paris saint germain": "psg",
    "paris saint-germain": "psg",
    "psg": "psg",
    "paris sg": "psg",
    "marseille": "marseille",
    "olympique marseille": "marseille",
    "om": "marseille",
    "monaco": "monaco",
    "as monaco": "monaco",
    "lyon": "lyon",
    "olympique lyonnais": "lyon",
    "ol": "lyon",
    "lille": "lille",
    "losc": "lille",
    "losc lille": "lille",
    "rennes": "rennes",
    "stade rennais": "rennes",
    "nice": "nice",
    "ogc nice": "nice",
    "lens": "lens",
    "rc lens": "lens",
    "nantes": "nantes",
    "fc nantes": "nantes",
    "strasbourg": "strasbourg",
    "rc strasbourg": "strasbourg",
    "montpellier": "montpellier",
    "reims": "reims",
    "stade de reims": "reims",
    "toulouse": "toulouse",
    "toulouse fc": "toulouse",
    "brest": "brest",
    "stade brestois": "brest",
    "clermont": "clermont",
    "clermont foot": "clermont",
    "lorient": "lorient",
    "fc lorient": "lorient",
    "le havre": "le_havre",
    "havre": "le_havre",
    "metz": "metz",
    "fc metz": "metz",
    "auxerre": "auxerre",
    "aj auxerre": "auxerre",
    "angers": "angers",
    "sco angers": "angers",
    "bordeaux": "bordeaux",
    "fc girondins de bordeaux": "bordeaux",
    "girondins": "bordeaux",
    "saint-etienne": "saint_etienne",
    "saint etienne": "saint_etienne",
    "asse": "saint_etienne",
    "sochaux": "sochaux",
    "fc sochaux": "sochaux",
    "paris fc": "paris_fc",
    "amiens": "amiens",
    "amiens sc": "amiens",
    "caen": "caen",
    "sm caen": "caen",
    "grenoble": "grenoble",
    "grenoble foot": "grenoble",
    "valenciennes": "valenciennes",
    "va": "valenciennes",
    "dijon": "dijon",
    "dijon fco": "dijon",
    "troyes": "troyes",
    "estac troyes": "troyes",
    "bastia": "bastia",
    "sc bastia": "bastia",
    "quevilly": "quevilly",
    "us quevilly-rouen": "quevilly",
    "nimes": "nimes",
    "nimes olympique": "nimes",
    "pau": "pau",
    "pau fc": "pau",
    "rodez": "rodez",
    "rodez af": "rodez",
    "annecy": "annecy",
    "fc annecy": "annecy",
    "concarneau": "concarneau",
    "us concarneau": "concarneau",
    "ajaccio": "ajaccio",
    "ac ajaccio": "ajaccio",
    "laval": "laval",
    "stade laval": "laval",
    "niort": "niort",
    "chamois niortais": "niort",
    "le mans": "le_mans",
    "le mans fc": "le_mans",

    # === NETHERLANDS — Eredivisie ===
    "ajax": "ajax",
    "afc ajax": "ajax",
    "psv": "psv",
    "psv eindhoven": "psv",
    "eindhoven": "psv",
    "feyenoord": "feyenoord",
    "az alkmaar": "az_alkmaar",
    "az": "az_alkmaar",
    "twente": "twente",
    "fc twente": "twente",
    "utrecht": "utrecht",
    "fc utrecht": "utrecht",
    "vitesse": "vitesse",
    "heerenveen": "heerenveen",
    "sparta rotterdam": "sparta_rotterdam",
    "nec": "nec",
    "nec nijmegen": "nec",
    "go ahead eagles": "go_ahead_eagles",
    "go ahead": "go_ahead_eagles",
    "fortuna sittard": "fortuna_sittard",
    "fortuna": "fortuna_sittard",
    "heracles": "heracles",
    "heracles almelo": "heracles",
    "zwolle": "zwolle",
    "pec zwolle": "zwolle",
    "excelsior": "excelsior",
    "sbv excelsior": "excelsior",
    "emmen": "emmen",
    "fc emmen": "emmen",
    "waalwijk": "waalwijk",
    "rkc waalwijk": "waalwijk",
    "cambuur": "cambuur",
    "sc cambuur": "cambuur",
    "groningen": "groningen",
    "fc groningen": "groningen",
    "almere": "almere",
    "almere city": "almere",

    # === BELGIUM — Jupiler Pro League ===
    "club brugge": "club_brugge",
    "brugge": "club_brugge",
    "anderlecht": "anderlecht",
    "rsc anderlecht": "anderlecht",
    "union sg": "union_sg",
    "sint-gillis": "union_sg",
    "antwerp": "antwerp",
    "royal antwerp": "antwerp",
    "gent": "gent",
    "kaa gent": "gent",
    "standard liege": "standard_liege",
    "standard": "standard_liege",
    "genk": "genk",
    "krc genk": "genk",
    "mechelen": "mechelen",
    "kv mechelen": "mechelen",
    "cercle brugge": "cercle_brugge",
    "stvv": "sint_truiden",
    "sint-truiden": "sint_truiden",
    "sint truiden": "sint_truiden",
    "kortrijk": "kortrijk",
    "kv kortrijk": "kortrijk",
    "eupen": "eupen",
    "as eupen": "eupen",
    "charleroi": "charleroi",
    "sporting charleroi": "charleroi",
    "oh leuven": "oh_leuven",
    "leuven": "oh_leuven",
    "westerlo": "westerlo",
    "kvc westerlo": "westerlo",
    "lommel": "lommel",
    "sk lommel": "lommel",

    # === PORTUGAL — Primeira Liga ===
    "benfica": "benfica",
    "sl benfica": "benfica",
    "porto": "porto",
    "fc porto": "porto",
    "sporting": "sporting_cp",
    "sporting cp": "sporting_cp",
    "sporting lisbon": "sporting_cp",
    "braga": "braga",
    "sc braga": "braga",
    "vitoria guimaraes": "vitoria_guimaraes",
    "guimaraes": "vitoria_guimaraes",
    "famalicao": "famalicao",
    "fc famalicao": "famalicao",
    "rio ave": "rio_ave",
    "moreirense": "moreirense",
    "moreirense fc": "moreirense",
    "estoril": "estoril",
    "estoril praia": "estoril",
    "portimonense": "portimonense",
    "gil vicente": "gil_vicente",
    "boavista": "boavista",
    "boavista fc": "boavista",
    "casa pia": "casa_pia",
    "casa pia ac": "casa_pia",
    "vizela": "vizela",
    "fc vizela": "vizela",
    "estrela amadora": "estrela_amadora",
    "chaves": "chaves",
    "gd chaves": "chaves",
    "arouca": "arouca",
    "fc arouca": "arouca",
    "farense": "farense",
    "sc farense": "farense",

    # === TURKEY — Super Lig + lower ===
    "galatasaray": "galatasaray",
    "galata": "galatasaray",
    "fenerbahce": "fenerbahce",
    "fb": "fenerbahce",
    "besiktas": "besiktas",
    "bjk": "besiktas",
    "trabzonspor": "trabzonspor",
    "trabzon": "trabzonspor",
    "basaksehir": "basaksehir",
    "medipol basaksehir": "basaksehir",
    "adana demirspor": "adana_demirspor",
    "adana": "adana_demirspor",
    "konyaspor": "konyaspor",
    "konya": "konyaspor",
    "antalyaspor": "antalyaspor",
    "antalya": "antalyaspor",
    "alanyaspor": "alanyaspor",
    "alanya": "alanyaspor",
    "kasimpasa": "kasimpasa",
    "gaziantep": "gaziantep",
    "gaziantep fk": "gaziantep",
    "kayserispor": "kayserispor",
    "kayseri": "kayserispor",
    "ankaragucu": "ankaragucu",
    "ankara gucu": "ankaragucu",
    "sivasspor": "sivasspor",
    "sivas": "sivasspor",
    "rizespor": "rizespor",
    "caykur rizespor": "rizespor",
    "hatayspor": "hatayspor",
    "hatay": "hatayspor",
    "umraniyespor": "umraniyespor",
    "istanbulspor": "istanbulspor",
    "eskisehirspor": "eskisehirspor",
    "aksehirspor": "aksehirspor",
    "bandirmaspor": "bandirmaspor",
    "giresunspor": "giresunspor",
    "altay": "altay",
    "altay sk": "altay",
    "boluspor": "boluspor",
    "genclerbirligi": "genclerbirligi",
    "ankaragucu sk": "ankaragucu",
    "tuzlaspor": "tuzlaspor",
    "manisa fk": "manisa",

    # === GREECE — Super League ===
    "olympiakos": "olympiacos",
    "olympiacos": "olympiacos",
    "panathinaikos": "panathinaikos",
    "pao": "panathinaikos",
    "paok": "paok",
    "aek athens": "aek_athens",
    "aek": "aek_athens",
    "aris": "aris",
    "aris thessaloniki": "aris",

    # === SCOTLAND — Premiership ===
    "celtic": "celtic",
    "celtic fc": "celtic",
    "rangers": "rangers",
    "glasgow rangers": "rangers",
    "aberdeen": "aberdeen",
    "hearts": "hearts",
    "heart of midlothian": "hearts",
    "hibernian": "hibernian",
    "hibs": "hibernian",
    "dundee united": "dundee_united",
    "dundee": "dundee",
    "st mirren": "st_mirren",
    "motherwell": "motherwell",
    "ross county": "ross_county",
    "kilmarnock": "kilmarnock",
    "st johnstone": "st_johnstone",
    "livingston": "livingston",
    "partick thistle": "partick_thistle",
    "inverness": "inverness",
    "inverness ct": "inverness",
    "queen of the south": "queen_of_south",
    "greenock morton": "morton",
    "morton": "morton",
    "arbroath": "arbroath",
    "ayr united": "ayr_united",
    "ayr": "ayr_united",
    "raith rovers": "raith_rovers",
    "dunfermline": "dunfermline",
    "dunfermline athletic": "dunfermline",
    "hamilton": "hamilton",
    "hamilton academical": "hamilton",

    # === DENMARK — Superliga ===
    "copenhagen": "copenhagen",
    "kobenhavn": "copenhagen",
    "fc copenhagen": "copenhagen",
    "fc kobenhavn": "copenhagen",
    "midtjylland": "midtjylland",
    "fc midtjylland": "midtjylland",
    "brondby": "brondby",
    "brondby if": "brondby",
    "agf": "agf",
    "agf aarhus": "agf",
    "aarhus": "agf",
    "aalborg": "aalborg",
    "aalborg bk": "aalborg",
    "viborg": "viborg",
    "viborg ff": "viborg",
    "silkeborg": "silkeborg",
    "silkeborg if": "silkeborg",
    "lyngby": "lyngby",
    "lyngby bk": "lyngby",
    "vejle": "vejle",
    "vejle bk": "vejle",
    "nordsjaelland": "nordsjaelland",
    "fc nordsjaelland": "nordsjaelland",
    "horsens": "horsens",
    "ac horsens": "horsens",
    "fredericia": "fredericia",
    "fc fredericia": "fredericia",

    # === NORWAY — Eliteserien ===
    "bodo/glimt": "bodo_glimt",
    "bodo glimt": "bodo_glimt",
    "bodoglimt": "bodo_glimt",
    "molde": "molde",
    "molde fk": "molde",
    "rosenborg": "rosenborg",
    "rbk": "rosenborg",
    "viking": "viking",
    "viking fk": "viking",
    "brann": "brann",
    "sk brann": "brann",
    "lorenskog": "lorenskog",
    "valerenga": "valerenga",
    "vif": "valerenga",
    "stromsgodset": "stromsgodset",
    "lillestrom": "lillestrom",
    "lsk": "lillestrom",
    "hamkam": "hamkam",
    "hamkam il": "hamkam",
    "sarpsborg": "sarpsborg",
    "sarpsborg 08": "sarpsborg",
    "tromso": "tromso",
    "tromso il": "tromso",
    "haugesund": "haugesund",
    "fk haugesund": "haugesund",
    "odd": "odd",
    "odd bk": "odd",
    "sandefjord": "sandefjord",
    "sandefjord fotball": "sandefjord",
    "kristiansund": "kristiansund",
    "kbk": "kristiansund",
    "aalesund": "aalesund",
    "fk aalesund": "aalesund",
    "stromsgodset if": "stromsgodset",

    # === SWEDEN — Allsvenskan + Superettan ===
    "malmo": "malmo",
    "malmo ff": "malmo",
    "aik": "aik",
    "aik stockholm": "aik",
    "djurgarden": "djurgarden",
    "djurgardens if": "djurgarden",
    "hammarby": "hammarby",
    "hammarby if": "hammarby",
    "goteborg": "goteborg",
    "ifk goteborg": "goteborg",
    "ifk g": "goteborg",
    "elfsborg": "elfsborg",
    "if elfsborg": "elfsborg",
    "hacken": "hacken",
    "bk hacken": "hacken",
    "norrkoping": "norrkoping",
    "ifk norrkoping": "norrkoping",
    "helsingborg": "helsingborg",
    "hif": "helsingborg",
    "kalmar": "kalmar",
    "kalmar ff": "kalmar",
    "sirius": "sirius",
    "ik sirius": "sirius",
    "varbergs": "varbergs",
    "varbergs bois": "varbergs",
    "gavle": "gavle",
    "gefle if": "gavle",
    "ostersund": "ostersund",
    "ifk ostersund": "ostersund",
    "degerfors": "degerfors",
    "degerfors if": "degerfors",
    "orebro": "orebro",
    "ifk orebro": "orebro",
    "orebro sk": "orebro",
    "osters": "osters",
    "osters if": "osters",
    "vasteras": "vasteras",
    "vasteras sk": "vasteras",
    "ik brage": "brage",
    "brage": "brage",
    "torslanda": "torslanda",
    "landskrona": "landskrona",
    "landskrona bois": "landskrona",

    # === FINLAND — Veikkausliiga ===
    "hjk": "hjk",
    "hjk helsinki": "hjk",
    "kuopion palloseura": "kups",
    "kups": "kups",
    "inter turku": "inter_turku",
    "fc inter turku": "inter_turku",
    "fc inter": "inter_turku",
    "haka": "haka",
    "valkeakosken haka": "haka",
    "ilves": "ilves",
    "ilves tampere": "ilves",
    "vps": "vps",
    "vps vaasa": "vps",
    "sjk": "sjk",
    "sjk seinajoki": "sjk",
    "seinajoki": "sjk",
    "ac oulu": "ac_oulu",
    "oulu": "ac_oulu",
    "fc lahti": "fc_lahti",
    "lahti": "fc_lahti",
    "if gnistan": "if_gnistan",
    "gnistan": "if_gnistan",
    "ff jaro": "ff_jaro",
    "jaro": "ff_jaro",
    "ifk mariehamn": "ifk_mariehamn",
    "mariehamn": "ifk_mariehamn",
    "tps": "tps",
    "turun palloseura": "tps",
    "turku": "tps",
    "lahti fc": "fc_lahti",

    # === SWITZERLAND — Super League ===
    "young boys": "young_boys",
    "bsc young boys": "young_boys",
    "basel": "basel",
    "fc basel": "basel",
    "zurich": "zurich",
    "fc zurich": "zurich",
    "lugano": "lugano",
    "fc lugano": "lugano",
    "luzern": "luzern",
    "fc luzern": "luzern",
    "servette": "servette",
    "st gallen": "st_gallen",
    "fc st gallen": "st_gallen",
    "grasshoppers": "grasshoppers",
    "gc": "grasshoppers",
    "winterthur": "winterthur",
    "fc winterthur": "winterthur",
    "lausanne": "lausanne",
    "lausanne sport": "lausanne",
    "sion": "sion",
    "fc sion": "sion",
    "thun": "thun",
    "fc thun": "thun",
    "vaduz": "vaduz",
    "fc vaduz": "vaduz",

    # === AUSTRIA — Bundesliga ===
    "salzburg": "salzburg",
    "red bull salzburg": "salzburg",
    "rb salzburg": "salzburg",
    "rapid vienna": "rapid_vienna",
    "rapid wien": "rapid_vienna",
    "rapid": "rapid_vienna",
    "austria vienna": "austria_vienna",
    "austria wien": "austria_vienna",
    "sturm graz": "sturm_graz",
    "sturm": "sturm_graz",
    "lask": "lask",
    "lask linz": "lask",
    "wolfsberger": "wolfsberger",
    "wolfsberg": "wolfsberger",
    "ried": "ried",
    "sv ried": "ried",
    "klagenfurt": "klagenfurt",
    "austria klagenfurt": "klagenfurt",
    "hartberg": "hartberg",
    "tsv hartberg": "hartberg",
    "altach": "altach",
    "scr altach": "altach",
    "wsg tirol": "wsg_tirol",
    "tirol": "wsg_tirol",
    "blau weiss linz": "bw_linz",
    "bw linz": "bw_linz",

    # === POLAND — Ekstraklasa ===
    "legia warsaw": "legia",
    "legia": "legia",
    "legia warszawa": "legia",
    "rakow czestochowa": "rakow",
    "rakow": "rakow",
    "lech poznan": "lech_poznan",
    "lech": "lech_poznan",
    "wisla krakow": "wisla_krakow",
    "wisla": "wisla_krakow",
    "piast gliwice": "piast",
    "piast": "piast",
    "pogon szczecin": "pogon",
    "pogon": "pogon",
    "jagiellonia bialystok": "jagiellonia",
    "jagiellonia": "jagiellonia",
    "slask wroclaw": "slask",
    "slask": "slask",
    "widzew lodz": "widzew",
    "widzew": "widzew",
    "radomiak radom": "radomiak",
    "radomiak": "radomiak",
    "korona kielce": "korona",
    "korona": "korona",
    "gornik zabrze": "gornik",
    "gornik": "gornik",
    "zaglebie lubin": "zaglebie",
    "zaglebie": "zaglebie",
    "cracovia": "cracovia",
    "rzszow": "rzszow",
    "resovia": "rzszow",
    "lechia gdansk": "lechia",
    "lechia": "lechia",
    "stal mielec": "stal_mielec",
    "warta poznan": "warta",
    "warta": "warta",
    "miedz legnica": "miedz",
    "motor lublin": "motor",
    "termalica": "termalica",
    "bruk-bet": "termalica",

    # === CZECH REPUBLIC — First League ===
    "sparta prague": "sparta_prague",
    "sparta praha": "sparta_prague",
    "sparta": "sparta_prague",
    "slavia prague": "slavia_prague",
    "slavia praha": "slavia_prague",
    "slavia": "slavia_prague",
    "viktoria plzen": "viktoria_plzen",
    "plzen": "viktoria_plzen",
    "banik ostrava": "banik_ostrava",
    "banik": "banik_ostrava",
    "jablonec": "jablonec",
    "fk jablonec": "jablonec",
    "mlada boleslav": "mlada_boleslav",
    "boleslav": "mlada_boleslav",
    "sigma olomouc": "sigma_olomouc",
    "olomouc": "sigma_olomouc",
    "tescoma zlin": "zlin",
    "zlin": "zlin",
    "hradec kralove": "hradec_kralove",
    "hradec": "hradec_kralove",
    "karvina": "karvina",
    "mfk karvina": "karvina",
    "slovan liberec": "liberec",
    "liberec": "liberec",
    "tescom zlin": "zlin",
    "pardubice": "pardubice",
    "fk pardubice": "pardubice",
    "bohemians": "bohemians_1905",
    "bohemians prague": "bohemians_1905",
    "ceske budejovice": "ceske_budejovice",
    "dynamo cb": "ceske_budejovice",
    "slovacko": "slovacko",
    "fc slovacko": "slovacko",
    "opava": "opava",
    "sfc opava": "opava",
    "trinec": "trinec",
    "fk trinec": "trinec",

    # === CROATIA — HNL ===
    "dinamo zagreb": "dinamo_zagreb",
    "dinamo": "dinamo_zagreb",
    "hajduk split": "hajduk_split",
    "hajduk": "hajduk_split",
    "rijeka": "rijeka",
    "hnk rijeka": "rijeka",
    "osijek": "osijek",
    "nk osijek": "osijek",
    "lokotmotiva zagreb": "lokomotiva_zagreb",
    "lokomotiva": "lokomotiva_zagreb",
    "istra 1961": "istra",
    "istra": "istra",
    "varazdin": "varazdin",
    "nk varazdin": "varazdin",
    "sibenik": "sibenik",
    "hnk sibenik": "sibenik",
    "slaven belupo": "slaven_belupo",
    "slaven": "slaven_belupo",
    "gorica": "gorica",
    "hnk gorica": "gorica",
    "rujevka": "rujevka",

    # === SERBIA — SuperLiga ===
    "red star belgrade": "red_star",
    "crvena zvezda": "red_star",
    "red star": "red_star",
    "partizan": "partizan",
    "partizan belgrade": "partizan",
    "vojvodina": "vojvodina",
    "novi sad": "vojvodina",
    "radnicki nis": "radnicki_nis",
    "radnicki 1923": "radnicki_nis",
    "cukaricki": "cukaricki",
    "cukaricki stankom": "cukaricki",
    "mladost lucani": "mladost",
    "mladost": "mladost",
    "baccka topola": "backa_topola",
    "backa": "backa_topola",
    "napredak krusevac": "napredak",
    "napredak": "napredak",
    "vojvodina ns": "vojvodina",
    "macva sabac": "macva",
    "metalac gornji milanovac": "metalac",
    "metalac": "metalac",
    "novi pazar": "novi_pazar",
    "kolkata": "kolkata",
    "rad beograd": "rad",
    "rad": "rad",
    "spartak subotica": "spartak_subotica",
    "radnik surdulica": "radnik_surdulica",
    "tsc": "tsc",
    "tscc": "tsc",
    "zeleznicar": "zeleznicar",

    # === HUNGARY — NB I ===
    "ferencvaros": "ferencvaros",
    "fradi": "ferencvaros",
    "ftc": "ferencvaros",
    "budapest honved": "honved",
    "honved": "honved",
    "debrecen": "debrecen",
    "dvsc": "debrecen",
    "dvtk": "diosgyor",
    "diosgyor": "diosgyor",
    "zalaegerszeg": "zalaegerszeg",
    "zte": "zalaegerszeg",
    "paksc": "paksc",
    "paksi fc": "paksc",
    "fehervar": "fehervar",
    "videoton": "fehervar",
    "puskas academy": "puskas_academy",
    "puskas": "puskas_academy",
    "keszthelyi": "keszthelyi",
    "u e budapest": "ue_budapest",
    "budafok": "budafok",
    "kisvarda": "kisvarda",
    "mezkovesd": "mezokovesd",
    "mezokovesd": "mezokovesd",
    "nyiregyhaza": "nyiregyhaza",

    # === ROMANIA — Superliga ===
    "cfr cluj": "cfr_1907_cluj",
    "cfr 1907 cluj": "cfr_1907_cluj",
    "cfr": "cfr_1907_cluj",
    "fcsb": "fcsb",
    "steaua": "fcsb",
    "steaua bucuresti": "fcsb",
    "universitatea craiova": "universitatea_craiova",
    "u craiova": "universitatea_craiova",
    "csi universitatea craiova": "universitatea_craiova",
    "fc universitatea cluj": "fc_universitatea_cluj",
    "universitatea cluj": "fc_universitatea_cluj",
    "sepsi": "sepsi",
    "sepsi osk": "sepsi",
    "farul constanta": "farul_constanta",
    "farul": "farul_constanta",
    "rapid bucuresti": "rapid_bucuresti",
    "petrolul ploiesti": "petrolul_ploiesti",
    "petrolul": "petrolul_ploiesti",
    "dinamo bucuresti": "dinamo_bucuresti",
    "ut alexandria": "ut_alexandria",
    "poli iasi": "poli_iasi",
    "hermannstadt": "hermannstadt",
    "chindia targoviste": "chindia_targoviste",
    "acs sepolu": "acs_sepolu",
    "univ. craiova": "universitatea_craiova",
    "arges": "arges",
    "scm gloria buzau": "gloria_buzau",

    # === BULGARIA — Parva Liga ===
    "cska sofia": "cska_sofia",
    "cska 1948": "cska_1948",
    "levski sofia": "levski",
    "levski": "levski",
    "ludogorets": "ludogorets",
    "razgrad": "ludogorets",
    "lokomotiv sofia": "lokomotiv_sofia",
    "loko sofia": "lokomotiv_sofia",
    "cherno more": "cherno_more",
    "cherno": "cherno_more",
    "botev plovdiv": "botev_plovdiv",
    "botev": "botev_plovdiv",
    "beroe": "beroe",
    "fc beree": "beroe",
    "pirin": "pirin",
    "etar": "etar",
    "etar veliko": "etar",

    # === RUSSIA — Premier League ===
    "zenit": "zenit",
    "zenit st petersburg": "zenit",
    "spartak moscow": "spartak_moscow",
    "spartak": "spartak_moscow",
    "cska moscow": "cska_moscow",
    "cska": "cska_moscow",
    "lokomotiv moscow": "lokomotiv_moscow",
    "loko moscow": "lokomotiv_moscow",
    "dynamo moscow": "dynamo_moscow",
    "dynamo": "dynamo_moscow",
    "krasnodar": "krasnodar",
    "fc krasnodar": "krasnodar",
    "rostov": "rostov",
    "fc rostov": "rostov",
    "rubin kazan": "rubin_kazan",
    "rubin": "rubin_kazan",
    "akhmat grozny": "akhmat",
    "akhmat": "akhmat",
    "terek": "akhmat",
    "sochi": "sochi",
    "fc sochi": "sochi",
    "ural yekaterinburg": "ural",
    "ural": "ural",
    "nizhny novgorod": "nizhny_novgorod",
    "khimki": "khimki",
    "fakel voronezh": "fakel",
    "fakel": "fakel",
    "krylia sovetov": "krylia_sovetov",
    "krylia": "krylia_sovetov",
    "amkar": "amkar",
    "tom tomsk": "tom_tomsk",
    "tom": "tom_tomsk",

    # === UKRAINE — Premier League ===
    "shakhtar donetsk": "shakhtar",
    "shakhtar": "shakhtar",
    "dynamo kyiv": "dynamo_kyiv",
    "dyk": "dynamo_kyiv",
    "zorya lugansk": "zorya",
    "zorya": "zorya",
    "dnipro": "dnipro",
    "fc dnipro": "dnipro",
    "vorskla poltava": "vorskla",
    "vorskla": "vorskla",
    "desna chernihiv": "desna",
    "desna": "desna",
    "kolos kovalivka": "kolos",
    "kolos": "kolos",
    "liviv": "liviv",
    "lviv": "liviv",
    "minaj": "minaj",
    "fc minaj": "minaj",
    "oles gun": "oles_gun",
    "ingulets": "ingulets",
    "veres rivne": "veres",
    "veres": "veres",
    "metalist kharkiv": "metalist",
    "metalist 1925": "metalist",
    "chornomorets": "chornomorets",
    "chornomorets odesa": "chornomorets",
    "ruk lviv": "ruk_lviv",
    "polissya zhytomyr": "polissya",
    "polissya": "polissya",

    # === BRAZIL — Serie A/B/C/D ===
    "flamengo": "flamengo",
    "flamengo rj": "flamengo",
    "palmeiras": "palmeiras",
    "sao paulo": "sao_paulo",
    "santos": "santos",
    "santos fc": "santos",
    "corinthians": "corinthians",
    "sc corinthians": "corinthians",
    "gremio": "gremio",
    "gremio porto alegre": "gremio",
    "internacional": "internacional",
    "internacional rs": "internacional",
    "inter rs": "internacional",
    "atletico mineiro": "atletico_mineiro",
    "atletico mg": "atletico_mineiro",
    "gallo": "atletico_mineiro",
    "fluminense": "fluminense",
    "botafogo": "botafogo",
    "botafogo rj": "botafogo",
    "botafogo sp": "botafogo_sp",
    "cruzeiro": "cruzeiro",
    "cruzeiro mg": "cruzeiro",
    "vasco": "vasco",
    "vasco da gama": "vasco",
    "vasco da gama rj": "vasco",
    "fortaleza": "fortaleza",
    "fortaleza ce": "fortaleza",
    "fortaleza ec": "fortaleza",
    "bahia": "bahia",
    "ec bahia": "bahia",
    "athletico paranaense": "athletico_paranaense",
    "atletico pr": "athletico_paranaense",
    "paranaense": "athletico_paranaense",
    "cuiaba": "cuiaba",
    "cuiaba mt": "cuiaba",
    "goias": "goias",
    "goias ec": "goias",
    "coritiba": "coritiba",
    "coritiba fc": "coritiba",
    "america mineiro": "america_mineiro",
    "america mg": "america_mineiro",
    "bragantino": "bragantino",
    "red bull bragantino": "bragantino",
    "bragantino sp": "bragantino",
    "vitoria": "vitoria_ba",
    "vitoria ba": "vitoria_ba",
    "vitoria salvador": "vitoria_ba",
    "criciuma": "criciuma",
    "criciuma ec": "criciuma",
    "juventude": "juventude",
    "juventude rs": "juventude",
    "chapecoense": "chapecoense",
    "chapecoense sc": "chapecoense",
    "avai": "avai",
    "avai fc": "avai",
    "operario pr": "operario_pr",
    "operario ferroviario": "operario_pr",
    "operario": "operario_pr",
    "vila nova": "vila_nova",
    "vila nova go": "vila_nova",
    "criciuma sc": "criciuma",
    "crb": "crb",
    "crb maceio": "crb",
    "clube de regatas brasil": "crb",
    "ceara": "ceara",
    "ceara sc": "ceara",
    "ceara fc": "ceara",
    "remo": "remo",
    "remo pa": "remo",
    "remo belem": "remo",
    "nautico": "nautico",
    "nautico capibaribe": "nautico",
    "mirassol": "mirassol",
    "mirassol sp": "mirassol",
    "atletico go": "atletico_goianiense",
    "atletico goianiense": "atletico_goianiense",
    "america rj": "america_rj",
    "ponte preta": "ponte_preta",
    "guarani": "guarani",
    "guarani campinas": "guarani",
    "londrina": "londrina",
    "londrina pr": "londrina",
    "ituano": "ituano",
    "ituano sp": "ituano",
    "brusque": "brusque",
    "brusque sc": "brusque",
    "tombense": "tombense",
    "novorizontino": "novorizontino",
    "gremio novorizontino": "novorizontino",
    "csa": "csa",
    "csa alagoas": "csa",
    "confianca": "confianca",
    "abc": "abc",
    "abc natal": "abc",
    "volta redonda": "volta_redonda",
    "botafogo pb": "botafogo_pb",
    "sampaio correia": "sampaio_correia",
    "vilhenense": "vilhenense",
    "manaus": "manaus",
    "manaus fc": "manaus",
    "ferroviaria": "ferroviaria",
    "aa ferroviaria": "ferroviaria",
    "nova iguacu": "nova_iguacu",
    "bangu": "bangu",
    "madureira": "madureira",
    "portuguesa": "portuguesa",
    "portuguesa santista": "portuguesa",

    # === ARGENTINA — Primera Division ===
    "boca juniors": "boca",
    "boca": "boca",
    "river plate": "river",
    "river": "river",
    "racing club": "racing",
    "racing": "racing",
    "independiente": "independiente",
    "san lorenzo": "san_lorenzo",
    "estudiantes": "estudiantes",
    "estudiantes lp": "estudiantes",
    "estudiantes de la plata": "estudiantes",
    "lanus": "lanus",
    "newells old boys": "newells",
    "newells": "newells",
    "rosario central": "rosario_central",
    "tigre": "tigre",
    "gimnasia lp": "gimnasia",
    "gimnasia": "gimnasia",
    "banfield": "banfield",
    "valez sarsfield": "valez_sarsfield",
    "velez": "velez_sarsfield",
    "velez sarsfield": "velez_sarsfield",
    "colon": "colon",
    "colon de santa fe": "colon",
    "argentinos juniors": "argentinos_juniors",
    "argentinos": "argentinos_juniors",
    "godoy cruz": "godoy_cruz",
    "platense": "platense",
    "huracan": "huracan",
    "central cordoba": "central_cordoba",
    "central cordoba santiago": "central_cordoba",
    "defensa y justicia": "defensa_y_justicia",
    "defensa": "defensa_y_justicia",
    "atletico tucuman": "atletico_tucuman",
    "talleres": "talleres",
    "talleres cordoba": "talleres",
    "instituto": "instituto",
    "instituto cordoba": "instituto",
    "united eagles": "united_eagles",
    "patronato": "patronato",
    "arsenal de sarandi": "arsenal_sarandi",
    "arsenal sarandi": "arsenal_sarandi",
    "sarmiento": "sarmiento",
    "sarmiento junin": "sarmiento",
    "central norte": "central_norte",
    "aldosivi": "aldosivi",
    "dock sud": "dock_sud",
    "belgrano": "belgrano",
    "belgrano cordoba": "belgrano",
    "deportivo riestra": "riestra",
    "riestra": "riestra",
    "all boys": "all_boys",
    "chacarita juniors": "chacarita",
    "chacarita": "chacarita",
    "mitre": "mitre",
    "mitre santiago del estero": "mitre",
    "gimnasia jujuy": "gimnasia_jujuy",
    "guillermo brown": "guillermo_brown",
    "nueva chicago": "nueva_chicago",
    "chicago": "nueva_chicago",
    "deportivo moron": "moron",
    "moron": "moron",
    "los andes": "los_andes",
    "estudiantes bs as": "estudiantes_buenos_aires",
    "estudiantes de caseros": "estudiantes_buenos_aires",
    "chacarita j": "chacarita",
    "atletico de rafaela": "rafela",
    "rafela": "rafela",
    "san martin tucuman": "san_martin_tucuman",
    "san martin": "san_martin_tucuman",
    "chaco for ever": "chaco_for_ever",
    "agropecuario": "agropecuario",
    "villa dalmine": "villa_dalmine",
    "defensores de belgrano": "defensores_belgrano",
    "villa maipu": "villa_maipu",

    # === CHILE — Primera Division ===
    "colo colo": "colo_colo",
    "colo-colo": "colo_colo",
    "universidad de chile": "uni_de_chile",
    "u de chile": "uni_de_chile",
    "u. de chile": "uni_de_chile",
    "universidad catolica": "uni_catolica",
    "u catolica": "uni_catolica",
    "u. catolica": "uni_catolica",
    "uc": "uni_catolica",
    "coquimbo": "coquimbo_unido",
    "coquimbo unido": "coquimbo_unido",
    "cobreloa": "cobreloa",
    "antofagasta": "antofagasta",
    "cd antofagasta": "antofagasta",
    "huachipato": "huachipato",
    "ohiggins": "ohiggins",
    "o'higgins": "ohiggins",
    "nubense": "nubense",
    "nublense": "nubense",
    "deportes iquique": "deportes_iquique",
    "iquique": "deportes_iquique",
    "union espanola": "union_espanola",
    "palestino": "palestino",
    "audax italiano": "audax_italiano",
    "everton de vina": "everton_vina",
    "everton vina": "everton_vina",
    "santiago wanderers": "santiago_wanderers",
    "curico": "curico_unido",
    "curico unido": "curico_unido",
    "union la calera": "union_la_calera",
    "la calera": "union_la_calera",
    "o'higgins rancagua": "ohiggins",
    "huachipato talcahuano": "huachipato",
    "deportes la serena": "la_serena",
    "la serena": "la_serena",
    "copiapo": "copiapo",
    "cd copiapo": "copiapo",
    "san luis de quillota": "san_luis",
    "san luis": "san_luis",
    "puerto montt": "puerto_montt",
    "deportes puerto montt": "puerto_montt",
    "temuco": "temuco",
    "deportes temuco": "temuco",
    "rangers de talca": "rangers_talca",
    "magallanes": "magallanes",
    "santiago morning": "santiago_morning",
    "barnechea": "barnechea",
    "ac barnechea": "barnechea",
    "copiapo sa": "copiapo",
    "recoleta": "recoleta",
    "deportes recoleta": "recoleta",
    "melipilla": "melipilla",
    "san marcos": "san_marcos",
    "san marcos de arica": "san_marcos",

    # === COLOMBIA — Primera A ===
    "atletico nacional": "atletico_nacional",
    "nacional medellin": "atletico_nacional",
    "nacional": "atletico_nacional",
    "deportes tolima": "deportes_tolima",
    "tolima": "deportes_tolima",
    "deportivo pereira": "deportivo_pereira",
    "pereira": "deportivo_pereira",
    "rionegro aguilas doradas": "rionegro_aguilas_doradas",
    "aguilas doradas": "rionegro_aguilas_doradas",
    "aguilas": "rionegro_aguilas_doradas",
    "junior": "junior_fc",
    "junior fc": "junior_fc",
    "junior de barranquilla": "junior_fc",
    "america de cali": "america_de_cali",
    "america cali": "america_de_cali",
    "millonarios": "millonarios",
    "once caldas": "once_caldas",
    "la equidad": "la_equidad",
    "patriotas": "patriotas",
    "envigado": "envigado",
    "envigado fc": "envigado",
    "jaguares de cordoba": "jaguares_de_cordoba",
    "jaguares": "jaguares_de_cordoba",
    "alianza petrolera": "alianza_petrolera",
    "atletico bucaramanga": "atletico_bucaramanga",
    "bucaramanga": "atletico_bucaramanga",
    "boyaca chico": "boyaca_chico",
    "chico": "boyaca_chico",
    "deportivo medellin": "deportivo_independiente_medellin",
    "medellin": "deportivo_independiente_medellin",
    "independiente medellin": "deportivo_independiente_medellin",
    "dim": "deportivo_independiente_medellin",
    "fortaleza caz": "fortaleza_caz",
    "fortaleza cazar": "fortaleza_caz",
    "agricola": "agricola",
    "deportivo pasto": "pasto",
    "pasto": "pasto",
    "atletico huila": "huila",
    "huila": "huila",
    "cortulua": "cortulua",
    "oriente valledupar": "valledupar",
    "valledupar": "valledupar",
    "jaguarss de cordoba": "jaguares_de_cordoba",

    # === MEXICO — Liga MX ===
    "club america": "club_america",
    "america": "club_america",
    "club de futbol america": "club_america",
    "guadalajara": "guadalajara",
    "chivas": "guadalajara",
    "cd guadalajara": "guadalajara",
    "monterrey": "monterrey",
    "rayados": "monterrey",
    "cf monterrey": "monterrey",
    "tigres uanl": "tigres",
    "tigres": "tigres",
    "tigres univ": "tigres",
    "pumas unam": "pumas",
    "pumas": "pumas",
    "unam": "pumas",
    "cruz azul": "cruz_azul",
    "tijuana": "tijuana",
    "club tijuana": "tijuana",
    "santos laguna": "santos_laguna",
    "santos l": "santos_laguna",
    "atlas": "atlas",
    "club atlas": "atlas",
    "pachuca": "pachuca",
    "cf pachuca": "pachuca",
    "toluca": "toluca",
    "deportivo toluca": "toluca",
    "leon": "leon",
    "club leon": "leon",
    "puebla": "puebla",
    "club puebla": "puebla",
    "queretaro": "queretaro",
    "gallos blancos": "queretaro",
    "atlas fc": "atlas",
    "mazatlan": "mazatlan",
    "fc juarez": "juarez",
    "juarez": "juarez",
    "club necaxa": "necaxa",
    "necaxa": "necaxa",
    "atletico san luis": "atletico_san_luis",
    "tijuana fc": "tijuana",

    # === USA — MLS + USL ===
    "inter miami": "inter_miami",
    "inter miami cf": "inter_miami",
    "la galaxy": "la_galaxy",
    "los angeles galaxy": "la_galaxy",
    "galaxy": "la_galaxy",
    "portland timbers": "portland_timbers",
    "portland": "portland_timbers",
    "timbers": "portland_timbers",
    "sporting kc": "sporting_kc",
    "sporting kansas city": "sporting_kc",
    "skc": "sporting_kc",
    "seattle sounders": "seattle_sounders",
    "sounders": "seattle_sounders",
    "atlanta united": "atlanta_united",
    "atlanta utd": "atlanta_united",
    "nycfc": "nycfc",
    "new york city": "nycfc",
    "new york city fc": "nycfc",
    "philadelphia union": "philadelphia_union",
    "phila union": "philadelphia_union",
    "orlando city": "orlando_city",
    "orlando": "orlando_city",
    "fc dallas": "fc_dallas",
    "dallas": "fc_dallas",
    "new york red bulls": "ny_red_bulls",
    "red bulls": "ny_red_bulls",
    "nyrb": "ny_red_bulls",
    "chicago fire": "chicago_fire",
    "columbus crew": "columbus_crew",
    "columbus": "columbus_crew",
    "fc cincinnati": "fc_cincinnati",
    "cincinnati": "fc_cincinnati",
    "nashville sc": "nashville",
    "nashville": "nashville",
    "charlotte fc": "charlotte_fc",
    "charlotte": "charlotte_fc",
    "st louis city": "st_louis_city",
    "stl city": "st_louis_city",
    "austin fc": "austin_fc",
    "austin": "austin_fc",
    "dc united": "dc_united",
    "houston dynamo": "houston_dynamo",
    "houston": "houston_dynamo",
    "real salt lake": "real_salt_lake",
    "rsl": "real_salt_lake",
    "colorado rapids": "colorado_rapids",
    "colorado": "colorado_rapids",
    "vancouver whitecaps": "vancouver_whitecaps",
    "vancouver": "vancouver_whitecaps",
    "montreal": "montreal",
    "cf montreal": "montreal",
    "toronto fc": "toronto_fc",
    "toronto": "toronto_fc",
    "san jose earthquakes": "san_jose_quakes",
    "san jose": "san_jose_quakes",
    "quakes": "san_jose_quakes",
    "new england revolution": "new_england_rev",
    "new england": "new_england_rev",
    "revs": "new_england_rev",
    "sacramento republic": "sacramento_republic",
    "sacramento": "sacramento_republic",
    "san diego fc": "san_diego",
    "san diego": "san_diego",
    "richmond kickers": "richmond_kickers",
    "richmond": "richmond_kickers",
    "chattanooga red wolves": "chattanooga_red_wolves",
    "chattanooga": "chattanooga_red_wolves",
    "corpus christi": "corpus_christi",
    "corpus christi fc": "corpus_christi",
    "fort wayne": "fort_wayne",
    "fort wayne fc": "fort_wayne",
    "one knoxville": "one_knoxville",
    "one knoxville sc": "one_knoxville",
    "fc naples": "fc_naples",
    "naples": "fc_naples",
    "north carolina fc": "north_carolina_fc",
    "lexington sc": "lexington",
    "lexington": "lexington",
    "westchester": "westchester",
    "fredricksburg": "fredricksburg",
    "spartanburg": "spartanburg",
    "avarta": "avarta",

    # === CANADA — CPL ===
    "forge fc": "forge",
    "forge": "forge",
    "pacific fc": "pacific",
    "pacific": "pacific",
    "inter toronto": "inter_toronto",
    "fc supra du quebec": "fc_supra_du_quebec",
    "supra du quebec": "fc_supra_du_quebec",
    "valour fc": "valour",
    "valour": "valour",
    "york united": "york_united",
    "york": "york_united",
    "york9": "york_united",
    "halifax wanderers": "halifax_wanderers",
    "halifax": "halifax_wanderers",
    "wanderers fc": "halifax_wanderers",
    "cavalry fc": "cavalry",
    "cavalry": "cavalry",
    "vancouver fc": "vancouver_fc_cpl",
    "vancouver cpl": "vancouver_fc_cpl",

    # === JAPAN — J1 League ===
    "urawa red diamonds": "urawa_reds",
    "urawa reds": "urawa_reds",
    "urawa": "urawa_reds",
    "reds": "urawa_reds",
    "yokohama f marinos": "yokohama_fm",
    "yokohama f. marinos": "yokohama_fm",
    "yokohama fm": "yokohama_fm",
    "marinos": "yokohama_fm",
    "kawasaki frontale": "kawasaki_frontale",
    "kawasaki": "kawasaki_frontale",
    "fc tokyo": "fc_tokyo",
    "tokyo": "fc_tokyo",
    "kashima antlers": "kashima_antlers",
    "kashima": "kashima_antlers",
    "antlers": "kashima_antlers",
    "cerezo osaka": "cerezo_osaka",
    "cerezo": "cerezo_osaka",
    "gamba osaka": "gamba_osaka",
    "gamba": "gamba_osaka",
    "nagoya grampus": "nagoya_grampus",
    "nagoya": "nagoya_grampus",
    "grampus": "nagoya_grampus",
    "hiroshima": "sanfrecce_hiroshima",
    "sanfrecce": "sanfrecce_hiroshima",
    "sanfrecce hiroshima": "sanfrecce_hiroshima",
    "vissel kobe": "vissel_kobe",
    "kobe": "vissel_kobe",
    "sagan tosu": "sagan_tosu",
    "tosu": "sagan_tosu",
    "shonan bellmare": "shonan_bellmare",
    "shonan": "shonan_bellmare",
    "bellmare": "shonan_bellmare",
    "shimizu s-pulse": "shimizu_s_pulse",
    "shimizu": "shimizu_s_pulse",
    "s-pulse": "shimizu_s_pulse",
    "avisa fukuoka": "avispa_fukuoka",
    "avispa": "avispa_fukuoka",
    "avispa fukuoka": "avispa_fukuoka",
    "hokkaido consadole sapporo": "consadole_sapporo",
    "consadole": "consadole_sapporo",
    "sapporo": "consadole_sapporo",
    "kyoto sanga": "kyoto_sanga",
    "kyoto": "kyoto_sanga",
    "sanga": "kyoto_sanga",
    "yokohama fc": "yokohama_fc",
    "kashiwa reysol": "kashiwa_reysol",
    "kashiwa": "kashiwa_reysol",
    "reysol": "kashiwa_reysol",
    "albirex niigata": "albirex_niigata",
    "niigata": "albirex_niigata",
    "machida zelvia": "machida_zelvia",
    "machida": "machida_zelvia",
    "zelvia": "machida_zelvia",
    "iwata": "jubilo_iwata",
    "jubilo": "jubilo_iwata",
    "jubilo iwata": "jubilo_iwata",

    # === KOREA — K League 1 ===
    "ulsan hyundai": "ulsan_hyundai",
    "ulsan": "ulsan_hyundai",
    "pohang steelers": "pohang_steelers",
    "pohang": "pohang_steelers",
    "jeonbuk hyundai motors": "jeonbuk",
    "jeonbuk": "jeonbuk",
    "fc seoul": "fc_seoul",
    "seoul": "fc_seoul",
    "suwon samsung bluewings": "suwon",
    "suwon": "suwon",
    "bluewings": "suwon",
    "daegu fc": "daegu",
    "daegu": "daegu",
    "incheon united": "incheon_united",
    "incheon": "incheon_united",
    "gangwon fc": "gangwon",
    "gangwon": "gangwon",
    "gwangju fc": "gwangju",
    "gwangju": "gwangju",
    "jeju united": "jeju_united",
    "jeju": "jeju_united",
    "daeon": "daeon",
    "sangju sangmu": "sangju",
    "sangju": "sangju",
    "kim cheon sangmu": "sangju",
    "anyang": "anyang",
    "chungju hummel": "chungju",
    "busan ipark": "busan",
    "busan": "busan",
    "gyeongnam": "gyeongnam",
    "suwon fc": "suwon_fc",

    # === CHINA — Chinese Super League ===
    "shanghai port": "shanghai_port",
    "shanghai sipg": "shanghai_port",
    "shandong taishan": "shandong_taishan",
    "shandong": "shandong_taishan",
    "beijing guoan": "beijing_guoan",
    "beijing": "beijing_guoan",
    "guangzhou fc": "guangzhou",
    "guangzhou evergrande": "guangzhou",
    "guangzhou": "guangzhou",
    "shanghai shenhua": "shanghai_shenhua",
    "shenhua": "shanghai_shenhua",
    "henan": "henan",
    "henan jianye": "henan",
    "wuhan three towns": "wuhan_three_towns",
    "wuhan": "wuhan_three_towns",
    "chengdu rongcheng": "chengdu",
    "chengdu": "chengdu",
    "zhejiang": "zhejiang",
    "zhejiang greentown": "zhejiang",
    "tianjin jinmen tiger": "tianjin",
    "tianjin teda": "tianjin",
    "tianjin": "tianjin",
    "meizhou hakka": "meizhou",
    "cangzhou mighty lions": "cangzhou",
    "cangzhou": "cangzhou",
    "qingdao hainiu": "qingdao",
    "qingdao": "qingdao",
    "shenzhen": "shenzhen",
    "shenzhen fc": "shenzhen",
    "nantong zhiyun": "nantong",
    "dalian": "dalian_pro",
    "dalian pro": "dalian_pro",
    "changchun yatai": "changchun",
    "changchun": "changchun",
    "qingdao west coast": "qingdao_west",
    "sichuan jiuniu": "sichuan",
    "sichuan": "sichuan",
    "hebei": "hebei",
    "hebei china fortune": "hebei",
    "chongqing liangjiang": "chongqing",
    "chongqing": "chongqing",
    "kunshan fc": "kunshan",

    # === AUSTRALIA — A-League ===
    "melbourne city": "melbourne_city",
    "melbourne victory": "melbourne_victory",
    "victory": "melbourne_victory",
    "sydney fc": "sydney",
    "sydney": "sydney",
    "western sydney wanderers": "western_sydney",
    "western sydney": "western_sydney",
    "adelaide united": "adelaide_united",
    "adelaide": "adelaide_united",
    "perth glory": "perth_glory",
    "perth": "perth_glory",
    "central coast mariners": "central_coast",
    "central coast": "central_coast",
    "mariners": "central_coast",
    "wellington phoenix": "wellington_phoenix",
    "wellington": "wellington_phoenix",
    "phoenix": "wellington_phoenix",
    "brisbane roar": "brisbane_roar",
    "brisbane": "brisbane_roar",
    "roar": "brisbane_roar",
    "newcastle jets": "newcastle_jets_au",
    "western united": "western_united",
    "macarthur fc": "macarthur",
    "macarthur": "macarthur",
    "bulls": "macarthur",

    # === SAUDI ARABIA — Pro League ===
    "al hilal": "al_hilal",
    "al hilal riyadh": "al_hilal",
    "hilal": "al_hilal",
    "al nassr": "al_nassr",
    "al nassr riyadh": "al_nassr",
    "nassr": "al_nassr",
    "al ahli": "al_ahli",
    "al ahli jeddah": "al_ahli",
    "ahli": "al_ahli",
    "al ittihad": "al_ittihad",
    "ittihad": "al_ittihad",
    "al shabab": "al_shabab",
    "shabab": "al_shabab",
    "al fateh": "al_fateh",
    "fateh": "al_fateh",
    "al taawon": "al_taawon",
    "taawon": "al_taawon",
    "al fateh club": "al_fateh",
    "al fayha": "al_fayha",
    "fayha": "al_fayha",
    "al khaleej": "al_khaleej",
    "khaleej": "al_khaleej",
    "al raed": "al_raed",
    "raed": "al_raed",
    "damac": "damac",
    "damac fc": "damac",
    "al wehda": "al_wehda",
    "wehda": "al_wehda",
    "abha": "abha",
    "abha club": "abha",
    "al fateh saudi": "al_fateh",
    "al hazem": "al_hazem",
    "hazem": "al_hazem",
    "al okhdood": "al_okhdood",
    "okhdood": "al_okhdood",
    "al riyadh": "al_riyadh",
    "riyadh": "al_riyadh",
    "al kholood": "al_kholood",
    "kholood": "al_kholood",

    # === MOROCCO — Botola Pro ===
    "raja club athletic": "raja_club_athletic",
    "raja casablanca": "raja_club_athletic",
    "raja": "raja_club_athletic",
    "wydad ac": "wydad_ac",
    "wydad casablanca": "wydad_ac",
    "wydad": "wydad_ac",
    "widad temara": "widad_temara",
    "as far rabat": "as_far_rabat",
    "far rabat": "as_far_rabat",
    "far": "as_far_rabat",
    "mas fes": "mas_fes",
    "mas de fes": "mas_fes",
    "fus rabat": "fus_rabat",
    "fus": "fus_rabat",
    "hassania dagadir": "hassania_dagadir",
    "husa agadir": "hassania_dagadir",
    "husa": "hassania_dagadir",
    "cod meknes": "cod_meknes",
    "ittihad tanger": "ittihad_tanger",
    "difaa el jadida": "difaa_el_jadida",
    "difaa hassani el-jadidi": "difaa_el_jadida",
    "union touarga sport": "union_touarga_sport",
    "union touarga": "union_touarga_sport",
    "touarga": "union_touarga_sport",
    "kawkab marrakech": "kacm_marrakech",
    "kacm marrakech": "kacm_marrakech",
    "kacm": "kacm_marrakech",
    "renaissance zemamra": "renaissance_zemamra",
    "rca zemamra": "renaissance_zemamra",
    "moghreb tetouan": "moghreb_tetouan",
    "maghreb tetouan": "moghreb_tetouan",
    "amal tiznit": "amal_tiznit",
    "rs berkane": "rs_berkane",
    "renaissance berkan": "renaissance_berkan",
    "renaissance berkane": "renaissance_berkan",

    # === ANGOLA — Girabola ===
    "kabuscorp scp": "kabuscorp_scp",
    "kabuscorp": "kabuscorp_scp",
    "petro de luanda": "petro_de_luanda",
    "petro luanda": "petro_de_luanda",
    "atletico petroleos de luanda": "petro_de_luanda",
    "petroleos de luanda": "petro_de_luanda",
    "petro": "petro_de_luanda",
    "primeiro de agosto": "primeiro_de_agosto",
    "1 de agosto": "primeiro_de_agosto",
    "primeiro agosto": "primeiro_de_agosto",
    "wiliete sc": "wiliete_sc",
    "wiliete": "wiliete_sc",
    "fc bravos do maquis": "fc_bravos_do_maquis",
    "bravos do maquis": "fc_bravos_do_maquis",
    "bravos": "fc_bravos_do_maquis",
    "interclube luanda": "interclube_luanda",
    "interclube": "interclube_luanda",
    "fc luanda": "fc_luanda",
    "cd lunda sul": "cd_lunda_sul",
    "lunda sul": "cd_lunda_sul",
    "cd sao salvador": "cd_sao_salvador",
    "sao salvador": "cd_sao_salvador",
    "desportivo da huila": "desportivo_da_huila",
    "desportivo huila": "desportivo_da_huila",
    "fc cabinda": "fc_cabinda",
    "sporting clube de cabinda": "fc_cabinda",
    "sagrada esperanca": "sagrada_esperanca",
    "recreativo do libolo": "recreativo_do_libolo",
    "recreativo da caala": "recreativo_da_caala",
    "academica petroleos do lobito": "academica_do_lobito",
    "academica do lobito": "academica_do_lobito",
    "1 de maio de benguela": "primeiro_de_maio_benguela",
    "primeiro de maio benguela": "primeiro_de_maio_benguela",

    # === NIGERIA — NPFL ===
    "shooting stars": "shooting_stars",
    "3sc": "shooting_stars",
    "kano pillars": "kano_pillars",
    "pillars": "kano_pillars",
    "enyimba": "enyimba",
    "enyimba fc": "enyimba",
    "rivers united": "rivers_united",
    "plateau united": "plateau_united",
    "remo stars": "remo_stars",
    "sunshine stars": "sunshine_stars",
    "kwara united": "kwara_united",
    "abia warriors": "abia_warriors",
    "akwa united": "akwa_united",
    "enugu rangers": "enugu_rangers",
    "rangers international": "enugu_rangers",
    "lobi stars": "lobi_stars",
    "niger tornadoes": "niger_tornadoes",
    "heartland": "heartland",
    "bayelsa united": "bayelsa_united",
    "doma united": "doma_united",
    "bendel insurance": "bendel_insurance",
    "gombe united": "gombe_united",
    "insurance": "bendel_insurance",
    "gwagwalada": "gwagwalada",
    "nasarawa united": "nasarawa_united",
    "nasarawa": "nasarawa_united",
    "sharks": "sharks",
    "sharks fc": "sharks",
    "wikki tourist": "wikki_tourist",
    "wikki": "wikki_tourist",

    # === VIETNAM — V.League ===
    "viettel": "viettel",
    "clb viettel": "viettel",
    "hong linh ha tinh": "hong_linh_ha_tinh",
    "ha tinh": "hong_linh_ha_tinh",
    "slna": "song_lam_nghe_an",
    "song lam nghe an": "song_lam_nghe_an",
    "ha noi": "ha_noi",
    "ha noi fc": "ha_noi",
    "hanoi": "ha_noi",
    "hoang anh gia lai": "hoang_anh_gia_lai",
    "hagl": "hoang_anh_gia_lai",
    "binh duong": "becamex_binh_duong",
    "becamex binh duong": "becamex_binh_duong",
    "nam dinh": "nam_dinh",
    "thep xuat nam dinh": "nam_dinh",
    "thanh hoa": "thanh_hoa",
    "dong thanh thanh hoa": "thanh_hoa",
    "hai phong": "hai_phong",
    "quang nam": "quang_nam",
    "da nang": "da_nang",
    "shb da nang": "da_nang",
    "binh dinh": "binh_dinh",
    "topenland binh dinh": "binh_dinh",
    "khanh hoa": "khanh_hoa",
    "sanna khanh hoa": "khanh_hoa",
    "hcmc": "hcmc",
    "ho chi minh city": "hcmc",
    "ho chi minh city fc": "hcmc",
    "hoa binh": "hoa_binh",
    "ba ria vung tau": "ba_ria_vung_tau",
    "cong an nhan dan": "cong_an_nhan_dan",
    "can": "cong_an_nhan_dan",

    # === MONTENEGRO — Prva CFL ===
    "fk arsenal tivat": "fk_arsenal_tivat",
    "arsenal tivat": "fk_arsenal_tivat",
    "fk decic": "fk_decic",
    "decic": "fk_decic",
    "fk otrant": "fk_otrant",
    "otrant": "fk_otrant",
    "fk mladost donja gorica": "fk_mladost_donja_gorica",
    "mladost donja gorica": "fk_mladost_donja_gorica",
    "mladost dg": "fk_mladost_donja_gorica",
    "fk buducnost podgorica": "fk_buducnost_podgorica",
    "buducnost": "fk_buducnost_podgorica",
    "buducnost podgorica": "fk_buducnost_podgorica",
    "fk sutorjeska": "fk_sutorjeska",
    "sutorjeska": "fk_sutorjeska",
    "fk iskra": "fk_iskra",
    "iskra": "fk_iskra",
    "fk jedinstvo": "fk_jedinstvo",
    "jedinstvo": "fk_jedinstvo",
    "fk borec": "fk_borec",
    "borec": "fk_borec",
    "fk munkgolija": "fk_munkgolija",
    "komovi": "komovi",
    "arsenal tivat fk": "fk_arsenal_tivat",

    # === AZERBAIJAN — Premyer Liqa ===
    "sabail": "sabail",
    "sabail fk": "sabail",
    "sebail": "sabail",
    "karvan evlakh": "karvan_evlakh",
    "karvan": "karvan_evlakh",
    "neftci": "neftci",
    "neftci pfc": "neftci",
    "neftchi": "neftci",
    "qarabag": "qarabag",
    "qarabag fk": "qarabag",
    "qarabag agdam": "qarabag",
    "garabagh": "qarabag",
    "zira": "zira",
    "zira fk": "zira",
    "sabah": "sabah",
    "sabah fk": "sabah",
    "sumqayit": "sumqayit",
    "sumgayit": "sumqayit",
    "kapaz": "kapaz",
    "kapaz pfc": "kapaz",
    "turran": "turran",
    "turran fk": "turran",
    "shamkir": "shamkir",
    "shamkir fc": "shamkir",
    "aminati": "aminati",
    "shahdag": "shahdag",
    "shahdag qusar": "shahdag",
    "agri": "agri",

    # === INTERNATIONAL ===
    "world cup": "world_cup",
    "fifa world cup": "world_cup",
    "world cup 2026": "world_cup",
    "euro": "euro",
    "uefa european championship": "euro",
    "euro 2024": "euro",
    "copa america": "copa_america",
    "conmebol copa america": "copa_america",
    "africa cup of nations": "afcon",
    "afcon": "afcon",
    "caf": "afcon",
    "caf nations cup": "afcon",
    "nations league": "nations_league",
    "uefa nations league": "nations_league",
    "champions league": "champions_league",
    "uefa champions league": "champions_league",
    "ucl": "champions_league",
    "europa league": "europa_league",
    "uefa europa league": "europa_league",
    "uel": "europa_league",
    "conference league": "conference_league",
    "uefa conference league": "conference_league",
    "uecl": "conference_league",
    "copa libertadores": "copa_libertadores",
    "conmebol libertadores": "copa_libertadores",
    "libertadores": "copa_libertadores",
    "copa sudamericana": "copa_sudamericana",
    "sudamericana": "copa_sudamericana",
    "conmebol sudamericana": "copa_sudamericana",
    "volos": "volos",
    "volos fc": "volos",
    "ofi": "ofi",
    "ofi crete": "ofi",
    "asteras tripolis": "asteras_tripolis",
    "asteras": "asteras_tripolis",
    "atromitos": "atromitos",
    "atromitos athens": "atromitos",
    "pas lamia": "pas_lamia",
    "lamia": "pas_lamia",
    "ionikos": "ionikos",
    "ionikos nikea": "ionikos",
    "panetolikos": "panetolikos",
    "panserraikos": "panserraikos",
    "kifisia": "kifisia",
    "ofk kifisia": "kifisia",
    "slavia sofia": "slavia_sofia",
    "arda": "arda",
    "arda kardzhali": "arda",
    "botev vratsa": "botev_vratsa",
    "lokomotiv plovdiv": "lokomotiv_plovdiv",
    "loko plovdiv": "lokomotiv_plovdiv",
    "hebar": "hebar",
    "hebar pazarnik": "hebar",
    "septemvri": "septemvri",
    "septemvri sofia": "septemvri",

    # === IRELAND — League of Ireland ===
    "shamrock rovers": "shamrock_rovers",
    "shamrock": "shamrock_rovers",
    "bohemians dublin": "bohemians_dublin",
    "bohs": "bohemians_dublin",
    "derry city": "derry_city",
    "derry": "derry_city",
    "shelbourne": "shelbourne",
    "shels": "shelbourne",
    "st patricks athletic": "st_patricks",
    "st pats": "st_patricks",
    "pats": "st_patricks",
    "drogheda united": "drogheda",
    "drogheda": "drogheda",
    "sligo rovers": "sligo_rovers",
    "sligo": "sligo_rovers",
    "dundalk": "dundalk",
    "dundalk fc": "dundalk",
    "waterford": "waterford",
    "waterford fc": "waterford",
    "galway united": "galway_united",
    "galway": "galway_united",
    "finn harps": "finn_harps",
    "cork city": "cork_city",
    "cork": "cork_city",

    # === TUNISIA — Ligue 1 ===
    "es tunis": "es_tunis",
    "etoile du sahel": "es_tunis",
    "etoile sportive du sahel": "es_tunis",
    "css": "css",
    "club sportif sfaxien": "css",
    "ca bizertin": "ca_bizertin",
    "club africain": "club_africain",
    "stade tunisien": "stade_tunisien",
    "us monastir": "us_monastir",
    "monastir": "us_monastir",
    "us ben guerdane": "us_ben_guerdane",
    "ben guerdane": "us_ben_guerdane",
    "metlaoui": "metlaoui",
    "olympique beja": "olympique_beja",
    "beja": "olympique_beja",
    "as marsa": "as_marsa",
    "marsa": "as_marsa",
    "js kairouan": "js_kairouan",
    "as soliman": "as_soliman",
    "soliman": "as_soliman",
    "us tatouine": "us_tataouine",
    "tataouine": "us_tataouine",

    # === NATIONAL TEAMS ===
    "germany": "germany",
    "ger": "germany",
    "england": "england",
    "eng": "england",
    "france nat": "france_nat",
    "fra": "france_nat",
    "spain nat": "spain_nat",
    "esp": "spain_nat",
    "italy nat": "italy_nat",
    "ita": "italy_nat",
    "netherlands nat": "netherlands_nat",
    "ned": "netherlands_nat",
    "holland": "netherlands_nat",
    "portugal nat": "portugal_nat",
    "por": "portugal_nat",
    "belgium nat": "belgium_nat",
    "bel": "belgium_nat",
    "croatia nat": "croatia_nat",
    "cro": "croatia_nat",
    "switzerland nat": "switzerland_nat",
    "sui": "switzerland_nat",
    "austria nat": "austria_nat",
    "aut": "austria_nat",
    "denmark nat": "denmark_nat",
    "den": "denmark_nat",
    "sweden nat": "sweden_nat",
    "swe": "sweden_nat",
    "norway nat": "norway_nat",
    "nor": "norway_nat",
    "poland nat": "poland_nat",
    "pol": "poland_nat",
    "ukraine nat": "ukraine_nat",
    "ukr": "ukraine_nat",
    "russia nat": "russia_nat",
    "rus": "russia_nat",
    "turkey nat": "turkey_nat",
    "tur": "turkey_nat",
    "greece nat": "greece_nat",
    "scotland nat": "scotland_nat",
    "sco": "scotland_nat",
    "wales": "wales",
    "wal": "wales",
    "ireland nat": "ireland_nat",
    "irl": "ireland_nat",
    "czech republic": "czech_republic",
    "cze": "czech_republic",
    "czechia": "czech_republic",
    "romania nat": "romania_nat",
    "rou": "romania_nat",
    "hungary nat": "hungary_nat",
    "hun": "hungary_nat",
    "serbia nat": "serbia_nat",
    "srb": "serbia_nat",
    "finland nat": "finland_nat",
    "fin": "finland_nat",
    "slovakia": "slovakia",
    "svk": "slovakia",
    "slovenia": "slovenia",
    "svn": "slovenia",
    "albania": "albania",
    "alb": "albania",
    "iceland": "iceland",
    "isl": "iceland",
    "montenegro nat": "montenegro_nat",
    "mne": "montenegro_nat",
    "georgia nat": "georgia_nat",
    "geo": "georgia_nat",
    "kosovo": "kosovo",
    "luxembourg": "luxembourg",
    "northern ireland": "northern_ireland",
    "nir": "northern_ireland",
    "brazil nat": "brazil_nat",
    "bra": "brazil_nat",
    "argentina nat": "argentina_nat",
    "arg": "argentina_nat",
    "uruguay nat": "uruguay_nat",
    "uru": "uruguay_nat",
    "colombia nat": "colombia_nat",
    "col": "colombia_nat",
    "chile nat": "chile_nat",
    "chi": "chile_nat",
    "peru nat": "peru_nat",
    "paraguay nat": "paraguay_nat",
    "par": "paraguay_nat",
    "ecuador nat": "ecuador_nat",
    "ecu": "ecuador_nat",
    "bolivia nat": "bolivia_nat",
    "bol": "bolivia_nat",
    "venezuela nat": "venezuela_nat",
    "ven": "venezuela_nat",
    "usa nat": "usa_nat",
    "mexico nat": "mexico_nat",
    "mex": "mexico_nat",
    "canada nat": "canada_nat",
    "costa rica": "costa_rica",
    "crc": "costa_rica",
    "honduras": "honduras",
    "jamaica": "jamaica",
    "panama nat": "panama_nat",
    "pan": "panama_nat",
    "guatemala": "guatemala",
    "el salvador": "el_salvador",
    "trinidad and tobago": "trinidad_tobago",
    "senegal": "senegal",
    "sen": "senegal",
    "nigeria nat": "nigeria_nat",
    "nga": "nigeria_nat",
    "egypt": "egypt",
    "egy": "egypt",
    "morocco nat": "morocco_nat",
    "mar": "morocco_nat",
    "algeria": "algeria",
    "alg": "algeria",
    "tunisia nat": "tunisia_nat",
    "tun": "tunisia_nat",
    "ghana": "ghana",
    "gha": "ghana",
    "cameroon": "cameroon",
    "cmr": "cameroon",
    "ivory coast": "ivory_coast",
    "civ": "ivory_coast",
    "south africa nat": "south_africa_nat",
    "mali": "mali",
    "burkina faso": "burkina_faso",
    "dr congo": "dr_congo",
    "cod": "dr_congo",
    "congo dr": "dr_congo",
    "guinea nat": "guinea_nat",
    "guinea bissau": "guinea_bissau",
    "angola nat": "angola_nat",
    "ang": "angola_nat",
    "zambia": "zambia",
    "zimbabwe": "zimbabwe",
    "japan nat": "japan_nat",
    "jpn": "japan_nat",
    "south korea": "south_korea",
    "kor": "south_korea",
    "korea republic": "south_korea",
    "australia nat": "australia_nat",
    "aus": "australia_nat",
    "saudi arabia nat": "saudi_arabia_nat",
    "ksa": "saudi_arabia_nat",
    "iran": "iran",
    "irn": "iran",
    "qatar": "qatar",
    "uae": "uae",
    "united arab emirates": "uae",
    "iraq": "iraq",
    "uzbekistan": "uzbekistan",
    "china nat": "china_nat",
    "chn": "china_nat",
    "thailand": "thailand",
    "tha": "thailand",
    "vietnam nat": "vietnam_nat",
    "vie": "vietnam_nat",
    "new zealand": "new_zealand",
    "nzl": "new_zealand",

    # ============================================================

    # ============================================================

    # ============================================================

    # ============================================================

    # ============================================================

    # ============================================================

    # === NEW ADDITIONS v9.5 ===
    "1 de maio": "primeiro_maio",
    "12 de octubre": "doce_de_octubre",
    "9 de octubre": "nueve_de_octubre",
    "academia cantolao": "cantolao",
    "academica lobito": "academica_lobito",
    "academico de viseu": "academico_viseu",
    "academico viseu": "academico_viseu",
    "ad alianza adli": "alianza_adli",
    "akhmat groznyi": "akhmat",
    "aktobe": "aktobe",
    "al ahly": "al_ahly",
    "al ahly cairo": "al_ahly",
    "al fahd": "al_fahd",
    "al kuwait": "kuwait_sc",
    "al orobah": "al_orobah",
    "al qadsiah": "al_qadsiah",
    "al riyadh sc": "al_riyadh",
    "al zulfah": "al_zulfah",
    "aldershot": "aldershot",
    "aldershot town": "aldershot",
    "alianza": "alianza_lima",
    "alianza lima": "alianza_lima",
    "always ready": "always_ready",
    "always ready bolivia": "always_ready",
    "amazonas": "amazonas",
    "amazonas fc": "amazonas",
    "ameliano": "sportivo_ameliano",
    "americano": "americano_py",
    "anapolis": "anapolis",
    "anapolis fc": "anapolis",
    "angel city": "angel_city",
    "angel city fc": "angel_city",
    "angostura": "angostura",
    "aranjuez": "aranjuez",
    "as gabes": "as_gabes",
    "as metlaoui": "metlaoui",
    "asec": "asec_mimosas",
    "asec mimosa": "asec_mimosas",
    "associao confianca": "confianca",
    "astana": "astana",
    "athletic bilbao fem": "athletic_bilbao_fem",
    "atletico fem": "atletico_madrid_fem",
    "atletico grau": "atletico_grau",
    "atletico madrid fem": "atletico_madrid_fem",
    "atletico rentistas": "rentistas",
    "aucas": "aucas",
    "aurora": "aurora_bo",
    "aurora cochabamba": "aurora_bo",
    "bac ninh": "bac_ninh",
    "bac ninh fc": "bac_ninh",
    "barcelona fem": "barcelona_fem",
    "barcelona guayaquil": "barcelona_sc",
    "barcelona sc": "barcelona_sc",
    "barcelona w": "barcelona_fem",
    "barnet": "barnet",
    "barra fc": "barra_fc",
    "bay fc": "bay_fc",
    "beitar jerusalem": "beitar_jerusalem",
    "belarus nat": "belarus_nat",
    "belasica": "belasica",
    "belasica petrich": "belasica",
    "betis fem": "betis_fem",
    "beveren": "sk_beveren",
    "bia saigon": "bia_saigon",
    "bih": "bosnia",
    "binacional": "binacional",
    "binh duong fc": "binh_duong",
    "birmingham legion": "birmingham_legion",
    "birmingham usl": "birmingham_legion",
    "bloom": "blooming",
    "blooming": "blooming",
    "blr": "belarus_nat",
    "bohemian": "bohemian_fc",
    "bohemians 1905": "bohemians_1905",
    "bohemians prag": "bohemians_1905",
    "bolivar": "bolivar",
    "bolivar la paz": "bolivar",
    "borac banja luka": "borac_banja_luka",
    "boreham wood": "boreham_wood",
    "borehamwood": "boreham_wood",
    "bosnia": "bosnia",
    "bosnia and herzegovina": "bosnia",
    "boston river": "boston_river",
    "botafogo paraiba": "botafogo_pb",
    "botosani": "fc_botosani",
    "braga b": "braga_b",
    "breidablik": "breidablik",
    "bromley": "bromley",
    "bromley fc": "bromley",
    "brusque fc": "brusque",
    "buxton": "buxton",
    "ca ha noi": "cahn",
    "ca hcmc": "ca_hcmc",
    "ca ho chi minh": "ca_hcmc",
    "caala": "caala",
    "cabinda": "cabinda",
    "cahn": "cahn",
    "cantolao": "cantolao",
    "carabobo": "carabobo",
    "carabobo fc": "carabobo",
    "caracas": "caracas_fc",
    "caracas fc": "caracas_fc",
    "carlos a manucci": "carlos_manucci",
    "carlos manucci": "carlos_manucci",
    "cd feirense": "feirense",
    "cd huila": "huila",
    "cd libolo": "libolo",
    "cd macara": "macara",
    "cd nacional": "nacional_madeira",
    "cd santa clara": "santa_clara",
    "cd trofense": "trofense",
    "celje": "celje",
    "celtic glasgow": "celtic",
    "cerro porteno": "cerro_porteno",
    "cerro porteno pp": "cerro_porteno",
    "cerro porteno py": "cerro_porteno",
    "cerro uruguay": "cerro_uy",
    "charleston": "charleston_battery",
    "charleston battery": "charleston_battery",
    "chesterfield": "chesterfield",
    "chesterfield fc": "chesterfield",
    "chicago red stars": "chicago_red_stars",
    "chiefs": "kaizer_chiefs",
    "chindia": "chindia",
    "cienciano": "cienciano",
    "club athletique bizertin": "ca_bizertin",
    "club atletico banfield": "banfield",
    "club atletico cerro": "cerro_uy",
    "club atletico penarol": "penarol",
    "club atletico tigre": "tigre",
    "club atletico velez": "velez_sarsfield",
    "club blooming": "blooming",
    "club bolivar": "bolivar",
    "club cienciano": "cienciano",
    "club danubio": "danubio",
    "club emelec": "emelec",
    "club guairena": "guairena",
    "club guarani": "guarani_py",
    "club lanus": "lanus",
    "club libertad": "libertad_py",
    "club nxt": "club_nxt",
    "club olimpia": "olibia",
    "club omnisports meknes": "cod_meknes",
    "com": "comoros",
    "comoros": "comoros",
    "corvinul": "corvinul",
    "corvinul hundoara": "corvinul",
    "courage": "nc_courage",
    "coxyde": "coxyde",
    "cristal": "sporting_cristal",
    "crusaders": "crusaders_fc",
    "crusaders fc": "crusaders_fc",
    "csd delfin": "delfin",
    "csikszereda": "csikszereda",
    "cska 1948 bg": "cska_1948",
    "cska 1948 sofia": "cska_1948",
    "cska sofia 1948": "cska_1948",
    "cumbaya": "cumbaya",
    "curacao": "curacao",
    "cusco fc": "cusco_fc",
    "cuw": "curacao",
    "da nang fc": "da_nang",
    "dagenham": "dagenham",
    "dagenham redbridge": "dagenham",
    "danubio": "danubio",
    "dash": "houston_dash",
    "defensa y justicia arg": "defensa_y_justicia",
    "defensor": "defensor_sporting",
    "defensor sporting": "defensor_sporting",
    "defensor uruguay": "defensor_sporting",
    "deinze": "deinze",
    "delfin": "delfin",
    "deportivo fem": "deportivo_fem",
    "deportivo la guaira": "deportivo_la_guaira",
    "deportivo tachira": "deportivo_tachira",
    "deraja el jadida": "dh_el_jadida",
    "detroit": "detroit_city",
    "detroit city": "detroit_city",
    "dh el jadida": "dh_el_jadida",
    "dila gori": "dila_gori",
    "dinamo batumi": "dinamo_batumi",
    "dinamo romania": "dinamo_bucuresti",
    "dinamo tbilisi": "dinamo_tbilisi",
    "diosgyori vtk": "diosgyor",
    "dobrudzha": "dobrudzha",
    "dobrudzha dobrich": "dobrudzha",
    "dock sud arg": "dock_sud",
    "doma": "doma_united",
    "dong nai": "dong_nai",
    "dong thanh": "dong_nai",
    "dorking": "dorking",
    "dorking wanderers": "dorking",
    "dynamo ceske budejovice": "dynamo_cb",
    "ebbsfleet": "ebbsfleet",
    "ebbsfleet united": "ebbsfleet",
    "edf logrono": "logrono_fem",
    "el mas fuerte": "the_strongest",
    "el paso": "el_paso",
    "el paso locomotive": "el_paso",
    "emelec": "emelec",
    "es sahel": "es_sahel_cl",
    "es tunis cl": "es_tunis",
    "est": "estonia",
    "estonia": "estonia",
    "estudiantes buenos aires": "estudiantes_buenos_aires",
    "estudiantes de merida": "estudiantes_merida",
    "estudiantes merida": "estudiantes_merida",
    "etar veliko tarnovo": "etar",
    "etoile du sahel cl": "es_sahel_cl",
    "fas rabat": "fas_rabat",
    "fbc melgar": "melgar",
    "fc akhmat": "akhmat",
    "fc aktobe": "aktobe",
    "fc arges": "fc_arges",
    "fc astana": "astana",
    "fc botosani": "fc_botosani",
    "fc csikszereda": "csikszereda",
    "fc fakel": "fakel",
    "fc hermannstadt": "hermannstadt",
    "fc kairat": "kairat",
    "fc khimki": "khimki",
    "fc krylia": "krylia_sovietov",
    "fc montana": "montana",
    "fc ordabasy": "ordabasy",
    "fc orenburg": "orenburg",
    "fc penafiel": "penafiel",
    "fc shakhtyor": "shakhtyor",
    "fc slovan": "slovan_bratislava",
    "fc spartak varna": "spartak_varna",
    "fc steaua": "fcsb",
    "fc tobol": "tobol",
    "fc tulsa": "tulsa",
    "fc ural": "ural",
    "fc voluntari": "voluntari",
    "fci videoton": "fehervar",
    "feirense": "feirense",
    "fenix montevideo": "fenix_uy",
    "fenix uruguay": "fenix_uy",
    "ferencvarosi": "ferencvaros",
    "figueirense": "figueirense",
    "figueirense fc": "figueirense",
    "finn": "finn_harps",
    "fk borac": "borac_banja_luka",
    "fk graficar": "graficar",
    "fk hradek kralove": "hradec_kralove",
    "fk javor": "javor",
    "fk mlada boleslav": "mlada_boleslav",
    "fk sarajevo": "sarajevo",
    "fk sloga": "sloga",
    "fk struga": "struga",
    "fk teplice": "teplice",
    "fk vozdovac": "vozdovac",
    "fk zalgiris": "zalgiris",
    "fk zeljeznicar": "zeljeznicar",
    "flora": "flora",
    "flora tallinn": "flora",
    "floresta": "floresta",
    "floresta ec": "floresta",
    "francs borains": "francs_borains",
    "gab": "gabon",
    "gabes": "as_gabes",
    "gabon": "gabon",
    "gainsborough": "gainsborough",
    "gais": "gais",
    "gambia": "gambia_nat",
    "gateshead": "gateshead",
    "gateshead fc": "gateshead",
    "general diaz": "general_diaz",
    "glentoran": "glentoran",
    "glentoran fc": "glentoran",
    "gmb": "gambia_nat",
    "gnk dinamo zagreb": "dinamo_zagreb",
    "godoy cruz antonio tomba": "godoy_cruz",
    "gor mahia": "gor_mahia",
    "goteborgs atlet och idrottssalskap": "gais",
    "gotham fc": "gotham_fc",
    "graficar": "graficar",
    "gremio rs": "gremio",
    "guabira": "guabira",
    "guairena": "guairena",
    "gualaceo": "gualaceo",
    "guarani asuncion": "guarani_py",
    "guarani fc": "guarani",
    "guarani paraguay": "guarani_py",
    "guarani py": "guarani_py",
    "hai": "haiti",
    "hai phong fc": "hai_phong",
    "haiti": "haiti",
    "hajer": "hajer",
    "hajer fc": "hajer",
    "halifax town": "halifax_town",
    "halmstad": "halmstad",
    "halmstads bk": "halmstad",
    "hapoel be er sheva": "hapoel_beer_sheva",
    "hapoel beer sheva": "hapoel_beer_sheva",
    "hapoel haifa": "hapoel_haifa",
    "hapoel tel aviv": "hapoel_tel_aviv",
    "hartford": "hartford_athletic",
    "hartford athletic": "hartford_athletic",
    "hb": "hb_thorshavn",
    "hb thorshavn": "hb_thorshavn",
    "heartland fc": "heartland",
    "hebar fc": "hebar",
    "horseforth": "horseforth",
    "houston dash": "houston_dash",
    "huntsville city": "huntsville_city",
    "idv": "independiente_del_valle",
    "ifk sandviken": "sandviken",
    "ifk vaxjo": "oster",
    "ikorodu": "ikorodu_city",
    "ikorodu city": "ikorodu_city",
    "imbabura": "imbabura",
    "independiente del valle": "independiente_del_valle",
    "independiente del valle cl": "independiente_del_valle",
    "independiente rivadavia": "independiente_rivadavia",
    "indianapolis eleven": "indianapolis_eleven",
    "indy eleven": "indianapolis_eleven",
    "instituto ac cordoba": "instituto",
    "inter de limeira": "inter_limeira",
    "inter lagos": "inter_lagos",
    "inter limeira": "inter_limeira",
    "ir tanger": "ir_tanger",
    "irt tanger": "ir_tanger",
    "itabaiana": "itabaiana",
    "ituano fc": "ituano",
    "javor": "javor",
    "jorge wilstermann": "wilstermann",
    "js kabylie": "js_kabylie",
    "jsk": "js_kabylie",
    "kac": "kac_marrakech",
    "kac marrakech": "kac_marrakech",
    "kairat": "kairat",
    "kaizer chiefs": "kaizer_chiefs",
    "kansas city current": "kc_current",
    "katsina": "katsina_united",
    "katsina united": "katsina_united",
    "kettering": "kettering",
    "kf shkendija": "shkendija",
    "kf shkupi": "shkupi",
    "kgz": "kyrgyzstan",
    "kisvarda fc": "kisvarda",
    "kmsk deinze": "deinze",
    "kraluv dvor": "kraluv_dvor",
    "krylia sovietov": "krylia_sovietov",
    "kuwait sc": "kuwait_sc",
    "kwara": "kwara_united",
    "kyrgyzstan": "kyrgyzstan",
    "la fc": "la_fc",
    "la guaira": "deportivo_la_guaira",
    "las vegas": "las_vegas_lights",
    "las vegas lights": "las_vegas_lights",
    "latvia": "latvia",
    "lbn": "lebanon",
    "lby": "libya",
    "ldu": "ldu_quito",
    "ldu quito": "ldu_quito",
    "lebanon": "lebanon",
    "leixoes": "leixoes",
    "leixoes sc": "leixoes",
    "levadia": "levadia",
    "levadia tallinn": "levadia",
    "levante fem": "levante_fem",
    "libertad": "libertad_py",
    "libertad fc": "libertad_fc_ec",
    "libolo": "libolo",
    "libya": "libya",
    "lierse": "lierse",
    "lierse kempenzonen": "lierse",
    "liga de quito": "ldu_quito",
    "ligat al": "ligat_al",
    "linfield": "linfield",
    "linfield fc": "linfield",
    "lithuania": "lithuania",
    "liverpool montevideo": "liverpool_uy",
    "liverpool uruguay": "liverpool_uy",
    "lok. pl": "lokomotiv_plovdiv",
    "lokoja": "lokoja",
    "lokomotiv pl": "lokomotiv_plovdiv",
    "lokomotiv plo": "lokomotiv_plovdiv",
    "los angeles fc": "la_fc",
    "loudoun": "loudoun_united",
    "loudoun united": "loudoun_united",
    "ltu": "lithuania",
    "luanda city": "luanda_city",
    "luqueno": "sportivo_luqueno",
    "lva": "latvia",
    "ma tetouan": "ma_tetouan",
    "macara": "macara",
    "maccabi haifa": "maccabi_haifa",
    "maccabi netanya": "maccabi_netanya",
    "maccabi tel aviv": "maccabi_tel_aviv",
    "macclesfield": "macclesfield",
    "macedonia": "north_macedonia",
    "madagascar": "madagascar",
    "madrid cff": "madrid_cff",
    "maidstone": "maidstone",
    "maidstone united": "maidstone",
    "malawi": "malawi",
    "mamelodi sundowns": "mamelodi_sundowns",
    "maranhao": "maranhao",
    "maribor": "maribor",
    "maringa": "maringa",
    "maringa fc": "maringa",
    "mauritania": "mauritania",
    "mazembe": "tp_mazembe",
    "mc alger": "mc_alger",
    "mdg": "madagascar",
    "melgar": "melgar",
    "memphis": "memphis_901",
    "memphis 901": "memphis_901",
    "metropolitanos": "metropolitanos",
    "mezokovesdi se": "mezokovesd",
    "miami": "miami_fc",
    "miami fc": "miami_fc",
    "minnesota": "minnesota_united",
    "minnesota united": "minnesota_united",
    "miramar misiones": "miramar_misiones",
    "mkd": "north_macedonia",
    "mladost novi sad": "mladost_ns",
    "mladost ns": "mladost_ns",
    "monagas": "monagas",
    "monagas sc": "monagas",
    "montana": "montana",
    "monterey": "monterey_bay",
    "monterey bay": "monterey_bay",
    "montevideo wanderers": "montevideo_wanderers",
    "moz": "mozambique",
    "mozambique": "mozambique",
    "mrt": "mauritania",
    "mwi": "malawi",
    "nacional asuncion": "nacional_asuncion",
    "nacional asuncion sud": "nacional_asuncion",
    "nacional madeira": "nacional_madeira",
    "nacional montevideo": "nacional_uy",
    "nacional potosi": "nacional_po",
    "nacional py": "nacional_asuncion",
    "nacional uruguay": "nacional_uy",
    "najran": "najran",
    "najran sc": "najran",
    "nam": "namibia",
    "nam dinh fc": "nam_dinh",
    "namibia": "namibia",
    "nc fc": "nc_fc",
    "nca": "nicaragua",
    "new mexico": "new_mexico_united",
    "new mexico united": "new_mexico_united",
    "new saints": "tns",
    "newell old boys": "newells",
    "nfc volos": "volos",
    "nicaragua": "nicaragua",
    "niger tornadoes fc": "niger_tornadoes",
    "niko niko": "niko_niko",
    "ninh binh": "ninh_binh",
    "ninh binh fc": "ninh_binh",
    "nizhny": "nizhny_novgorod",
    "nj ny gotham": "gotham_fc",
    "nk celje": "celje",
    "nk maribor": "maribor",
    "north carolina courage": "nc_courage",
    "north macedonia": "north_macedonia",
    "novi sad mladost": "mladost_ns",
    "ny red bulls": "ny_red_bulls",
    "oakland": "oakland_roots",
    "oakland roots": "oakland_roots",
    "oc safi": "oc_safi",
    "odevold": "odevold",
    "og ariana": "og_ariana",
    "ohod": "ohod",
    "ohod fc": "ohod",
    "ol reign": "ol_reign",
    "oldham": "oldham",
    "oldham athletic": "oldham",
    "olhanense": "olhanense",
    "olibia": "olibia",
    "olimpia": "olibia",
    "olimpia paraguay": "olibia",
    "olympique de gremda": "og_ariana",
    "olympique safi": "oc_safi",
    "ordabasy": "ordabasy",
    "orenburg": "orenburg",
    "orgryte": "orgryte",
    "orgryte is": "orgryte",
    "orient petrolero": "orient_petrolero",
    "orlando pirates": "orlando_pirates",
    "orlando pride": "orlando_pride",
    "orobah": "al_orobah",
    "oster": "oster",
    "otelul": "otelul",
    "otelul galati": "otelul",
    "paks": "paks",
    "palestine": "palestine",
    "patro maasmechelen": "patro_maasmechelen",
    "patronato arg": "patronato",
    "paysandu": "paysandu",
    "paysandu fc": "paysandu",
    "penafiel": "penafiel",
    "penarol": "penarol",
    "penarol uruguay": "penarol",
    "pfc slavia": "slavia_sofia",
    "pirates": "orlando_pirates",
    "pittsburgh": "pittsburgh",
    "pittsburgh riverhounds": "pittsburgh",
    "plateau": "plateau_united",
    "plaza colonia": "plaza_colonia",
    "ple": "palestine",
    "portland thorns": "portland_thorns",
    "portuguesa fc": "portuguesa_ve",
    "pride": "orlando_pride",
    "primeiro de maio": "primeiro_maio",
    "progreso": "progreso",
    "pvp pomorie": "pomorie",
    "pyramids": "pyramids",
    "pyramids fc": "pyramids",
    "qadsiah": "al_qadsiah",
    "racing casablanca": "racing_casablanca",
    "racing club de montevideo": "racing_uy",
    "racing louisville": "racing_louisville",
    "racing montevideo": "racing_uy",
    "radnik": "radnik_surdulica",
    "raja ca": "raja_casablanca",
    "rapid romania": "rapid_bucuresti",
    "rayo vallecano fem": "rayo_vallecano_fem",
    "rayo zuliano": "rayo_zuliano",
    "real atlas": "real_atlas",
    "real madrid fem": "real_madrid_fem",
    "real santa cruz": "real_santa_cruz",
    "real sociedad fem": "real_sociedad_fem",
    "real tomas": "real_tomas",
    "red stars": "chicago_red_stars",
    "reign fc": "ol_reign",
    "rentistas": "rentistas",
    "rhode island": "rhode_island",
    "rhode island fc": "rhode_island",
    "riga": "riga_fc",
    "riga fc": "riga_fc",
    "river plate montevideo": "river_plate_uy",
    "river plate uruguay": "river_plate_uy",
    "rivers": "rivers_united",
    "rovers ireland": "shamrock_rovers",
    "rowdies": "tampa_bay",
    "royal pinto": "royal_pinto",
    "royals": "utah_royals",
    "rs berkane maroc": "rs_berkane",
    "rwdm": "rwdm",
    "rwdm molenbeek": "rwdm",
    "samgurali": "samgurali",
    "san antonio": "san_antonio",
    "san antonio fc": "san_antonio",
    "san diego wave": "san_diego_wave",
    "sandviken": "sandviken",
    "santa clara": "santa_clara",
    "santa cruz": "santa_cruz",
    "santa cruz fc": "santa_cruz",
    "sao salvador do congo": "sao_salvador",
    "sarajevo": "sarajevo",
    "sc olhanense": "olhanense",
    "scunthorpe nl": "scunthorpe",
    "sd aucas": "aucas",
    "seattle reign": "ol_reign",
    "sevilla fem": "sevilla_fem",
    "shakhtyor": "shakhtyor",
    "sheriff": "sheriff_tiraspol",
    "sheriff tiraspol": "sheriff_tiraspol",
    "shkendija": "shkendija",
    "shkupi": "shkupi",
    "simba": "simba",
    "simba sc": "simba",
    "sk beveren": "sk_beveren",
    "skovde": "skovde",
    "skovde aik": "skovde",
    "sl16 fc": "sl16_fc",
    "sloga": "sloga",
    "slovan": "slovan_bratislava",
    "slovan bratislava": "slovan_bratislava",
    "slovany liberec": "liberec",
    "sol de america": "sol_de_america",
    "solihull": "solihull",
    "solihull moors": "solihull",
    "south sudan": "south_sudan",
    "southend": "southend",
    "southend united": "southend",
    "spartak varna": "spartak_varna",
    "spirit": "washington_spirit",
    "spokane": "spokane_velocity",
    "spokane velocity": "spokane_velocity",
    "sport boys warnes": "sport_boys",
    "sport huancayo": "sport_huancayo",
    "sporting cristal": "sporting_cristal",
    "sporting huelva": "huelva_fem",
    "sporting lagos": "sporting_lagos",
    "sportivo ameliano": "sportivo_ameliano",
    "sportivo luqueno": "sportivo_luqueno",
    "ssd": "south_sudan",
    "st patrick": "st_patricks",
    "stockport nl": "stockport",
    "struga": "struga",
    "suduva": "suduva",
    "suduva marijampole": "suduva",
    "sundowns": "mamelodi_sundowns",
    "sur": "suriname",
    "suriname": "suriname",
    "sv zulte waregem": "zulte_waregem",
    "syr": "syria",
    "syria": "syria",
    "tachira": "deportivo_tachira",
    "tacobeni": "tacobeni",
    "tajikistan": "tajikistan",
    "tampa bay": "tampa_bay",
    "tampa bay rowdies": "tampa_bay",
    "tecnico universitario": "tecnico_universitario",
    "tenerife fem": "tenerife_fem",
    "teplice": "teplice",
    "thanh hoa fc": "thanh_hoa",
    "the new saints": "tns",
    "the strongest": "the_strongest",
    "the strongest bo": "the_strongest",
    "thorns": "portland_thorns",
    "tjk": "tajikistan",
    "tns": "tns",
    "tobol": "tobol",
    "tomapo": "tomapo",
    "tomas chacabuco": "tomas_chacabuco",
    "tombense fc": "tombense",
    "torpedo zhodino": "torpedo_zhodino",
    "torquay": "torquay",
    "torquay united": "torquay",
    "tot overijse": "tot_overijse",
    "tp mazembe": "tp_mazembe",
    "trelleborg": "trelleborg",
    "trelleborgs ff": "trelleborg",
    "trofense": "trofense",
    "tsc backa topola": "tsc",
    "tulsa": "tulsa",
    "u cluj": "u_cluj",
    "udg tenerife": "tenerife_fem",
    "union touarga sportive": "uts_rabat",
    "unipro sochi": "sochi",
    "universidad catolica ecuador": "universidad_catolica_ec",
    "universidad catolica quito": "universidad_catolica_ec",
    "universidad de san martin": "san_martin_pe",
    "universitario": "universitario_pe",
    "universitario de deportes": "universitario_pe",
    "universitario lima": "universitario_pe",
    "us tataouine": "us_tataouine",
    "us zarzis": "zarzis",
    "uta": "uta_arad",
    "uta arad": "uta_arad",
    "utah royals": "utah_royals",
    "utc": "utc_pe",
    "uts rabat": "uts_rabat",
    "utskanken": "utskanken",
    "uzhhorod": "uzhhorod",
    "valencia fem": "valencia_fem",
    "valmiera": "valmiera",
    "valmiera fc": "valmiera",
    "varberg": "varberg",
    "varzim": "varzim",
    "varzim sc": "varzim",
    "vasteras city": "vasteras",
    "vikingur": "vikingur_reykjavik",
    "vikingur gotha": "vikingur_gotha",
    "vikingur reykjavik": "vikingur_reykjavik",
    "vila real": "vila_real",
    "vila real fc": "vila_real",
    "villarreal fem": "villarreal_fem",
    "vipers": "vipers",
    "vipers sc": "vipers",
    "vitez": "vitez",
    "volta redonda fc": "volta_redonda",
    "voluntari": "voluntari",
    "vozdovac": "vozdovac",
    "wanderers uruguay": "montevideo_wanderers",
    "warri wolves": "warri_wolves",
    "washington spirit": "washington_spirit",
    "wave": "san_diego_wave",
    "wealdstone": "wealdstone",
    "wealdstone fc": "wealdstone",
    "wiliete de cambambe": "wiliete_sc",
    "wilstermann": "wilstermann",
    "woking": "woking",
    "woking fc": "woking",
    "wrexham nl": "wrexham",
    "ws temara": "ws_temara",
    "yanga sc": "young_africans",
    "yeovil": "yeovil",
    "yeovil town": "yeovil",
    "young africans": "young_africans",
    "ypiranga": "ypiranga",
    "ypiranga fc": "ypiranga",
    "zalaegerszegi te": "zalaegerszeg",
    "zalgiris": "zalgiris",
    "zamalek": "zamalek",
    "zamalek sc": "zamalek",
    "zamora": "zamora",
    "zamora fc": "zamora",
    "zarzis": "zarzis",
    "zeljeznicar": "zeljeznicar",
    "zepceljak sarajevo": "sarajevo",
    "zulte waregem": "zulte_waregem",


    # === __main__ test pairs — underscored/hyphenated variants ===
    "atletico_go": "atletico_goianiense",
    "botafogo-rj": "botafogo",
    "botafogo-sp": "botafogo_sp",
    "botafogo_rj": "botafogo",
    "bragantino_sp": "bragantino",
    "clb_viettel": "viettel",
    "clube_de_regatas_brasil": "crb",
    "crb_maceio": "crb",
    "cruzeiro-mg": "cruzeiro",
    "cruzeiro_mg": "cruzeiro",
    "cuiaba_mt": "cuiaba",
    "fc_inter_turku": "inter_turku",
    "fortaleza-ce": "fortaleza",
    "fortaleza_ce": "fortaleza",
    "fortaleza_ec": "fortaleza",
    "gremio_porto_alegre": "gremio",
    "internacional_rs": "internacional",
    "jordan_[w]": "jordan_w",
    "kuopion_palloseura": "kups",
    "operario_ferroviario": "operario_pr",
    "red_bull_bragantino": "bragantino",
    "remo_belem": "remo",
    "vasco_da_gama-rj": "vasco",
    "vitoria_salvador": "vitoria_ba",
}

# ============================================================
# clean_team_name — simple normalization per §19.2
# ============================================================

def clean_team_name(name: str) -> str:
    """Нормализация названия команды."""
    key = name.strip().lower()
    return TEAM_ALIASES.get(key, key.replace(" ", "_"))

def build_canonical_id(home_team: str, away_team: str, date_utc: str) -> str:
    """
    Build canonical match ID from team names and date.
    Format: {home_clean}__{away_clean}__{YYYYMMDD}
    Per §1.18, §3 of architectural guide.
    """
    home_clean = clean_team_name(home_team)
    away_clean = clean_team_name(away_team)

    # Extract YYYYMMDD from date_utc (ISO 8601)
    date_str = ""
    if date_utc:
        # Handle formats: "2026-09-21T18:00:00Z", "2026-09-21", "2026-01-15T20:00:00Z"
        date_part = date_utc.strip()[:10]  # Take first 10 chars (YYYY-MM-DD)
        if len(date_part) >= 10 and date_part[4] == "-" and date_part[7] == "-":
            date_str = date_part[:4] + date_part[5:7] + date_part[8:10]

    if not home_clean or not away_clean:
        return ""
    if not date_str:
        return ""

    return f"{home_clean}__{away_clean}__{date_str}"


if __name__ == "__main__":
    # Test pairs from match dump
    pairs = [
        ("cruzeiro-mg", "cruzeiro"),
        ("botafogo_rj", "botafogo"),
        ("fortaleza_ce", "fortaleza"),
        ("fortaleza_ec", "fortaleza"),
        ("internacional_rs", "internacional"),
        ("vitoria_salvador", "vitoria_ba"),
        ("remo_belem", "remo"),
        ("gremio_porto_alegre", "gremio"),
        ("crb_maceio", "crb"),
        ("operario_ferroviario", "operario_pr"),
        ("red_bull_bragantino", "bragantino"),
        ("bragantino_sp", "bragantino"),
        ("clb_viettel", "viettel"),
        ("fc_inter_turku", "inter_turku"),
        ("gnistan", "if_gnistan"),
        ("kuopion_palloseura", "kups"),
        ("clube_de_regatas_brasil", "crb"),
        ("atletico_go", "atletico_goianiense"),
        ("cuiaba_mt", "cuiaba"),
        ("vasco_da_gama-rj", "vasco"),
        ("jordan_[w]", "jordan_w"),
        ("botafogo-sp", "botafogo_sp"),
        ("kobenhavn", "copenhagen"),
        ("bodo/glimt", "bodo_glimt"),
        ("colo-colo", "colo_colo"),
        ("cruzeiro_mg", "cruzeiro"),
        ("botafogo-rj", "botafogo"),
        ("fortaleza-ce", "fortaleza"),
    ]

    passed = 0
    failed = 0
    for a, b in pairs:
        ca = clean_team_name(a)
        cb = clean_team_name(b)
        if ca == cb:
            passed += 1
        else:
            failed += 1
            print(f"FAIL: {a} -> {ca} != {b} -> {cb}")

    print(f"\nDump pairs: {passed}/{len(pairs)} passed, {failed} failed")

    # Safety tests — should NOT match
    safety = [
        ("inter_milan", "internacional"),
        ("botafogo", "botafogo_sp"),
        ("fortaleza", "fortaleza_caz"),
        ("arsenal", "arsenal_sarandi"),
        ("chelsea", "celtic"),
        ("inter_turku", "inter_milan"),
    ]
    sp = 0
    sf = 0
    for a, b in safety:
        if clean_team_name(a) != clean_team_name(b):
            sp += 1
        else:
            sf += 1
            print(f"SAFETY FAIL: {a} == {b} -> {clean_team_name(a)}")

    print(f"Safety: {sp}/{len(safety)} passed, {sf} failed")

    # Count stats
    print(f"\nTotal aliases: {len(TEAM_ALIASES)}")
    unique_canonical = len(set(TEAM_ALIASES.values()))
    print(f"Unique canonical names: {unique_canonical}")
