name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-html pytest-cov

    - name: Run tests
      run: |
        pytest tests/  # Теперь указываем правильную директорию

    - name: Generate HTML report
      run: |
        pytest tests/ --html=test-reports/report.html --self-contained-html

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-reports/report.html
        
